using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using ITapply.Models.Responses;
using Microsoft.EntityFrameworkCore;
using static ITapply.Models.Responses.EnumResponse;

namespace ITapply.Services.Database
{
    public static class DataSeeder
    {
        private const string PdfBase64 = "JVBERi0xLjcKJeLjz9MKOSAwIG9iago8PAovT3JkZXJpbmcgKElkZW50aXR5KQovUmVnaXN0cnkgKEFkb2JlKQovU3VwcGxlbWVudCAwCj4+CmVuZG9iagoxMSAwIG9iago8PAovTGVuZ3RoMSAyMTQzNgovRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDk0MzgKPj4Kc3RyZWFtCnic7XsJeFRFunbVOb0lne509k46SXfTJAE6IewERNKQBZIQIJDG7kAgIQkEDBCSsC9GVNQo7huuuDvi0mlAgis6jvsu466jM87oqCiOyygKuW+drysGRrn3+tz7zPX5/9N5+33rq+XU+aq+Oh+PLeOMsRjWyVTmmzE7f8R1j9bvgeU5oK5hdYdrX+sboxnjuYzpH1zUunjZ5vfUsYwZPmbM4l3csm7RbaPvNDCWmMiYdV5zU33jdyevCzE2oBX9xzTDYLlb90+U70B5YPOyjrUdM80OlDG+4Y2WFQ31lzXv+ISxwbcwpi5fVr+2NfHKrDcZy8N4zLW8fllT+nVjMlEehTmsb13R3tHrYFsZGxoS9a1tTa0JiwekovwShv+UqTovv4jpmUm/XT8SPTKJ1ZfYVoWZmBKrVxRFpyq6D9nQ3v1s4AaMEgWwytkuF/MxlvWcgR1l/HHj9Uq2i/FeUafu1VvF3RjmZLyesaOXsv7XTLaUtcN/nZjXNnYpe4S9zRayM6C2sx3sNvY7FmKPsqfZ6+x/8Dq6Tr+Mxah7mYElMNZ7uPfg0duAHsz0J8ulKCXoXD9Zem29nx9n+/zopb22oz2GeBat9bUor8D6FT/Se1gpFOXeMaKsnA0dq/X40nj90XuP3n6cD6pYDZvL5rFaVsfq8fyNrJktgWdOZS1sGVuulZajbjG+F6G0AK0a0Eron1qtYK1AG+tgq9hqfFqh2yMlUbdSK69ia/BZy9ax9WwD28g2Rb7XaJaNqFmvldcCm9lpWJnT2RZNSSbLGexMdhZW7Wx2Djv3hKVz+1QXO4+dj3W+gF34i3rbMaWL8LmYXYL9cBm7nF3BrsK+uIZde5z1Ss1+Nbue3YA9I+ouh+UGTYnaB9kTbA+7h93L7tN82QCvkUekXxZpPmyFDzbiCc/oN2Py35o+b23Gs4tn64o86VrYt/TrsTriR9HyDLSkUWgdxCibjvPERXgG0j89EZUu157/J2t/r5zIKv1xbT/PXKOVhDre+kv6CnYdIvBGfAuvCnUTNKkbNN3ffn1f2x1a+WZ2C7sVa3G7piST5Tbo29kdiO072U52Fz4/6f6K+B52t7ZyIdbNwmwX242VvI/tZT2a/UR1P2ffFbGH+yz72P3sAeyQh9l+nDSP4SMtD8H2SMT6uGaj8mPs9yiLVlR6gj2JE+oZ9izO/RfZH1B6Qft+CqWX2CvsVfY6t0C9zP6O7yPsJf2HzMom4Z1wP/x8LZuPz//ipU9jSWxH73e9a3q/U6eyRbyaPwe/3gSvnM85zo2+iztZtO7POKl3936rzgMPOvKWvvnoTb1f+Gq2ntXR3raydcXyZS2nLl3SvHhRU+PCBfNr582tCQb81bNnVc2cMb1yWkV52dQppSXFRZMn+QonnjzhpPHjCsaOGZ0/NC93UHbWQM8Apz0xzhZrMUdHmYwGPV4mnOWWeErrXKHsupAu2zN1ap4oe+phqO9nqAu5YCo9tk3IVac1cx3b0oeWi45r6aOWvr6W3OaawCbk5bpKPK7Q88UeVw+vqQpAbyv2BF2hg5qu1LQuWytYUHC70cNVYm8udoV4naskVLq6uaukrhjjdZujizxFTdF5uaw72gxphgoN8rR280ETuSaUQSXju/EqtYjbhtSskvrG0MyqQEmxw+0OajZWpI0VMhSFjNpYriVizuw8V3fu/q7ze2xsYZ03ptHTWD8vEFLr0alLLenqOjsU5w0N9hSHBq//0I5HbgrleopLQl4PBquY1XcDHtJn2Tyurm8YJu85+NmxlvqIxZBl+4YJKR6xz02ol5phbpghns/tFnM5r8fHFqIQ6qwKUNnFFjrCzJfvDYaUOlGzX9Yk+UVNp6zp617ncYulKqmL/K1utoc6F7rycuF97S8Lf6h3hdTsuoUNzYLrm7o8xcXkt+pAyFcM4auPPGtJ97B8tK+vw0MsEW6oCoTyPa2hRM9kagCDS6zBktkBrUukWyixKITcLdIrlF9SLOblKumqK6YJirE8VYF9bGTv+92jXI5dI9koFhTzCCUXYVGyS7oCjYtCzjpHI/bnIlfA4Q75gnBf0BNoCopV8thCg9/H7dzaHbVeeLbjWsvG4smNWSZXQHGoQbFaMLhK8eWZPAEVNiyXVhQrOnmCK8AdTDbDXSIthDpmHBTUrKKpokoVXYumOtxBN10nmJIjMid9VsjUbywbDH1zovv84tSotZjQYFdJU3G/CR4zqD4ywchoPz9PRfgicmP0MInlnCqr1CxELmwKhtFMYhXtrhCb6Qp4mjxBD/aQb2ZAPJvwtba+FbM9FVU1AW21I7uk+pgS1RdQKcTcqJYFpQh7sNTrkMuqlado5b7i1OOqy2S1R8yrq6uxm6lZYis7urkm9EXnBUMzvEFPaKHX4xbzzMvtNrEYd3VdEWK1FMedp7Te47K5Srvqe3o7F3Z1+3xdrSV1zeMRF12essYuz+zABIc2+VmBTY714t7xrIJXVE/GUAqb3O3h51R1+/g5s2sC+2zI1M+pDoQVrhTVTQ52D0RdYJ+LMZ9mVYRVGEXBJQpipFkomLT2jn0+xjq1Wp1m0MoNPZxpNpO0cdbQo5DNRjfK1m7kYwpqdFTjk611sJnI1kmtB0Vam1BjEzX3M7xImFZJVzcTDvZF630mX5QvRrEocKkwhWG5H22jONsVwy3c0Y0xZ2nmHt7ZHeVz7NNGmhVp2YmWwtbZZ8PMRbN+A+F+9OD+n57AXxPYFcMwvvaNFpPFhV1ob8YewvukxNUo9t/GYHNXXVCcHiwZexV/PMQ9E1lI8UzEjA0xoWhP0+SQ2TNZ2AuFvZDsBmE3YufzZI7FFoduV50HBzEiJsAcnGJNFUO6enp7qwPu5x0Hg27E0jygJhCK8uLlps8qR7spAnUwTwl1NtSLeTB/QPQ1ZpU1BBGXckA0KQtFYYSoyAhoUar1EfGGTg3Ya/UeTcKMo6MzGAp6xU0DS4JavNpCbKpnfMiQTWPqs8WN8oNd8Z4R2uGDWI/OOltQFObGZgfI4kARNwuSk4wxmHmDB1UNdS7aI7MRy/SyiHaQpQlnvi67SUO0I1LJxGOpWWZLdChqKAbEn9DmoeLM0WcZg0GavFY6O9IA97aFzJhRdj9XRjrAO6gqE3PB39mYqmj6qBimqofN8qzF0SkmrY1kRHXIklVWj7cb9TfD4imQnU3iEDRHxnicrEbx5DHwO46Ent7bPevc/S6cHeLtJ/Yfc+xDoLJg1/GG0FxvXq7peKtFM3d1mSw/34H8ZbL0sWZUshrEWwEsNpy231wl4lXpKe9Wpns15hp3lXvwBlGyBJDoqAgft6sxKFphyjO1s+wXG/F+jcRrWhu8y3aSLPFIiRazK7T42GJzX7FUAMlg1lDKIfAo4qzFXlnqCLVgZ8omYkVcXS6bZ7xHfGmdpwjUYZH6wgLbH7tOBE1ngyuwEJsdA5bWdZV2iRS1oT7itsidQsu9xwyJuODYPBhIPE6oc6arLuiqQ2rKqwJutwPRCHYtQp7qqRevgpn0PDNrtFSlvktscYZMJegIGfFiWlTf5HHjDRISJxB5X8xRFwkb5ujq8nSFtLgtRWMMn42wKxOEv1avp75JpNCLRAbdpPUtxXQ174jRHCUexHITzJov4TgcfQvFV0OXSNBr67zwRFxXfJdrXBeO4Fq8PXTZDXPq8KoSbySXttT1DpTghDJRCmIgahiVJRpSCIjZLPN21xqzfrJofyu81NikjYqZzQqEZsomWjwJsdIbUlIKUCkens+qCchzShXVZXCvD7vKIXq7Qkp1ILI8Wv8y0dUhF4y6waK9QyLx1fe2ke+heQ749Bft+AcXY0fb1Vf0VqYyIxvHKtl0dmXoLG/gQbwJZrFkNp7v2ZNUXGzKMz7Mi/DCcPFqvMo4L/LF6hTL3rS0Qs/e0YZtalxZD8/bXWjcpiis8Mh7R17IP/Lewfhx+Qd5/rsfvPeB7csX4sblj/zgwAfDhzl8iWmWvS3oOtqzt2W0atjWosYViv6+qJZCn2Lc1oJB7IXetBe8L+R7X/BiGO+w4UEe547TkGhVjMZEg2fAUGV0TvaYkSNHTFRGj8r2DLAqmm3UmLET1ZEjMhU1UVomKqLM1Vd+rFFnHDEomz2Fc0bqM9NiEy0GvZJuj8+bkGWbPTdrwtAMo2o0qHqTcdDYyQMqWkoGvGWMy0hKzog3meIzkpMy4oxH3tZbD/9Db/2hSNfyw2Wq4aR5hQPVq6JNis5g6Mm0pw45yV02JzbBpjMn2OKSTcb4uJhBxfOObE1KF2OkJyXRWEcqkVvU9x7Sxegz4XnN67vS2Unent6Pd9l4JfjQrliNP9tl0fhzpAGVWr0Z/LAyEv82t/N85mbZPDecMFv3AB/CRrNhfGh31Bwsw4GDAjz/A6+4bK89Dud3u+09PH9Xizshu4fn7m5JmD1a18OH7GoZHTWshw8Nt6AnfP+4VwBez0q0Gvr50JAU8anwdlJipiKcL3yri1H0pkTfgg1lm5+9sHL2FS+fVrC0ptRh0qs6k9lkHTFj5Yw52xrHjm64aG5le9WoWGO0Qd1rs8dbEwfnOKpv+fK6G3+8d16Sa4jDmpAWn5ieEJWTn1Oy9dGNGx46bVJ2frYhLhOpDrsLYXshdms8c7KrhMd8GYVunmCHvxJscFZCIjyVEA83Jdjho4QHlBF4VaSRR9MiHtXYovG3wqNpEY+mPaDEsSh4NCZsrXL08OxufTUrPFjY58EDRMOH1Tq6rXBjzO4Wa5VetAy3oCncVqhtVOEi94Ds0XGjxox0wzfGUfCXJ064SnfhnFsP3Xb085TBg1N41h0fX1e1Z9SKO7fe273xzrZxytV3/HDrLGeObkuO85SbP96+ZM+Z5T/GTex8FDtlQO9hXbM+kQ1kW+m5B5ow5UEDeZrg7DQ+KIVnW3huKs+181Q80e5YG5+miRgLn2aXFiF88cKUak+1Z2c5Z9n18bP0flZYGD+uMC6ejxuXn09PyWpreW1trbfW69jb18yutRMbw6piH+hyeHb2mDFiB6TwkVzEXXKywajs1VlTczKS3fa4GKN6NGji8YMGpLvjo3S8nfMlqilxYKZzoEU1ZZqtJpXr9NgjunCyw6pTTZboHx7RFQq73upIZnj2mt6Dqkt9Glv7KfHs3emsp3e/WFHw+2IlmXg6uIHlRIInJ7LUOZGgyYksMfgT0SGnRzH7LPlWbk39yOmLtkx1Duzhyu6EcvXT4Rh7d5Rl6vDcHm7ojqoUceQ9qH3x/FraAY8DI8RJFuNM/aiFBkgQI+xtSSgfrn7aIgbZIwaJEqMgqCopqLSo+vmwMlBUGfoHlepS9MbUCRWB/PormkZPWrk96K0qHm2PMijxlticCf7xa05z+2onjJtT6I0xRhvVm+JS4yypWRnxvg27Vp31yPqTbGkD7NYEe3yO0z3IvfeeU84IeAd6PaaEDMRSLby6XX2Gedko9om2p4bkjykcs2KMmuASUeQS8ZTgzrXBf7kimnJtFvEldhGe6vs9xd5bvIo4pvaIY2qULrIYuojPtbJZY9p6uh4l2ud25z7ZqbtIp+zX8Zd0XKdLz38nu9z+SZ211apYoz5J1xxei6jDsV+7sk0G34h3veR88TbQQtA3QJf7ZMtqbYzs/Hdassut9k9amNVmVWJVa3rUJy3p5PUF82vhdzEcRafB4+7n46RjV0JJyhmjvUqM6vac1CPhzNLWKl9jWX6M0WxQFdVoHjNnpW/F7W3jJ6zc0bD08rq829R1a06eN3EA/sWZ465YO2doUlqS0Zoab0mIjTGn2hMmru9Z37Hv9JLi9msCCVsuGzqtaazY09t7D+tfgvdn8kzN9454mzlyamXbzDF8Wo5dfLfO4qUJkXMqIbKJE8TmtkU4VmNtUyf08O98mZnJkJmZI6Kj0SVaLFm0GDRaW7dorNvemb44XjlzYk5k2H6xcei42NGOyZwH+HdsBLNhH1eUY5MbfJZJ5RNL8wrK8qalTtNPw8khzoRx/U/KcQe8msBL3xuxYMmYEI7uChsG2d1SUT5JG83acuxwdjkenaZZ8iUeN0qLD2PcCQyRJUyKnEiUBiTpXzLFu+yprgRTYm7x0HHtJaYElz3FnWBMzi0aOq6jGLWpdleC0RCfnpKcYTNOu7CsIFg8zJZXVTFl4Cmry5yp4ngS7zHFM25+8cCA/8h5v2xRzzSZo1Q1ymxa45+Rlj9p0PDiIQknLzp3Gq26ugOrPoL1aKseS6suvgpH8SE/s7KHaGWP3wFYaUem2Ya2ZrHEZvHyM4sVN4vFNqN+L/OhyDKFs33ReeVDUgeWyeXCCY6lkktjO2aFHN15WhdzS78+dur0n63Hse5PUneQ3+NN9qFlwyZu/FdHX1lZs2Ga+yf3xlaeyJlwYp3IAsT74D14MYHlsKc1P6YXDuaD4vngOPEOzI7h2SaebeRDVD5Y4ZmRd0JmxKmZkXMqM3JOZUacmimOp8z8aB6dKPKJROHSRHESJop8IlH4NfF+JZqx3v17Y1llK5YztYfzcGy5Byd/t74ykivURtwqXxZwq7wc3bGiy+6W2HK96IS0ofLYtKHfQaRlDf2yLPW98e13t624dfmYce13tYPH3uOYuHRG2ZJit6Nw6YypS4td/K/L922tmLx5dxu4HLyxbMvCcaMWbKks31I/btT8LeLkcfd+oSzT3c3Gs3OF73YPZnGevIhv8iIbLi+y4fIivsuL+ChPbLyYFEveQc/UDMvBlKnDe7iu20iP/rx4+pH00COef1x7QWLogy1om+JLsRxsSZlqFB3CLcbIY6fZnpebSkd7yIO8SThgZN95nESntAEZVGKyPLWVZSaba/DQlNJGX8bm2Hi9yWLaZEygzfaRKSZKFx/70dgpKQPTE036KL1ubsYAmzXKkFXRPl2xugYmpMUZXzOilS4qBiIuLWGg62h07YKo6Ci91Q4fXYYddq36YF+cOhGd5hwRaTkiyHJEzpWjnag5Nu3o5N/fx8SxypwRDzojHgR/p739hBAuFA2k4RAZ+Pe+qIS8shyzPrUMR6J+l7VSi9OD2jEoz1TvgX5HqcMXFelgFT2QiFZSmHq1Pv3jdLTBcGx4xmkbaszYPoN6rTE+IyklI85QeYUWkMZElx1xakrJnzps4oYSY6ITYRsf1Rena/zTJyw+d6EyQAbnka9nLCjKCviVVdIidhpjhvEfDF/yVeeC2AnfsCiT9l/uHvh0o/jNCXu9bM2MHw4f6Yz6zDSGiV9nKPI/7aGb9tuM6B0/HD68I+ozbaR+F79PZ+1XevHX//dGXTGr/1n7Z+JfGr+dy/D6b2u+/S9dFxvw77iv+ixb9nN2XRO78Zh2nceW/69dBgO7UXfxz89Rdydb9GvHVQ/+155bDbL0Y+65jd3wX77HEeb+787rf+JSF7KaE9UbONXrRrG6Y/r9wGr/F6f1//RlaGTb4e/tv1SvKzjxmp3oUp755XFP2O+eX78/9Qn/vb549stAj/znH35Kv8+B3+JHmfX/P7/yc+SXP+qDv6WPbq++5pjP97/2Yzjv13yMQ2MLRWbJ72OdzMYmIP9UwPnsbMbixwz8FHUi7zTi1FERneLXwx0AaY53XkdEK8zKLopolY1i10e0Dm1eiWg9S2afR7SBpXMdq9Z+3dnOXJHvemARW8GWY1wXWxP57WdzX30Ha9J+9Sl+NVsPLGEtbJ1Wu1z7xWY9yi1o08iGwlqMdi7td7ZitFVo0YTTaBKbwoL4TGWTmZcVaX2WsIXaaLPQYjFatmijz8QIpfgX4ol6jGfD8BmO+w3TPidqOweji1/0LtGe0BXpdaIemqfF1WsXvwP/16s7Sp00W3lKeYIVMKfyZITfZQXKW8yvvAl+HfxGhF8D/xF8APwq+BXwy+BHwA+DHwI/yPxMp7zNRgHVgNqnGoFbgAOAnp2KkTgzoz9nicpjrBhoBDqAywA92j6MulswImcu5czdUXZe7upRzpBiixSnS9EpxWlSbJZikxQbpdggxXop1kmxVoo1UqyWYpUUHVK0S7FSilYpVkixXIplUrRIcaoUS6VYIkWzFIulWCRFkxSNUjRIsVCKeinqpFggxXwpaqWYJ8VcKWqkCEoRkOIUKeZI4ZeiWorZUsySokqKmVLMkGK6FJVSTJOiQopyKcqkmCrFFClKpSiRoliKIikmSzFJCp8UhVJMlOJkKSZIcZIU46UYJ0WBFGOlGCPFaClGSTFSihFSDJdimBT5UgyVIk+KXCm8UgyRYrAUg6TIkSJbiiwpBkrhkWKAFG4pXFI4pciUIkOKdCkcUqRJkSqFXYoUKZKlSJIiUYoEKeKliJPCJkWsFFYpLFLESGGWIlqKKClMUhilMEihl0InhSqFIgWXgkUE75XiqBRHpPhRih+kOCzF91J8J8U/pfhWim+k+FqKr6T4hxRfSnFIii+k+FyKg1J8JsWnUnwixd+l+FiKj6T4mxR/leJDKf4ixZ+l+ECK96X4kxTvSfGuFO9I8bYUb0nxphRvSPG6FK9J8UcpDkjxqhSvSPGyFC9J8aIUL0jxvBTPSfGsFM9I8bQUT0nxpBRPSPEHKR6X4vdSPCbFo1Lsl+IRKR6W4iEpHpTiASnul2KfFD1S7JXiPin2SLFbil1ShKXoliIkxb1S3CPF3VLcJcVOKe6U4ndS3CHF7VLcJsWtUtwixc1S3CTFjVLskOIGKa6X4joprpXiGimulmK7FFdJcaUUV0hxuRSXSXGpFJdIcbEUF0lxoRQXSLFNivOlOE+KLinOleIcKc6WYqsUZ0kh0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x4u0x7eJoXMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7jMf7hMe7hMe7hMe7jMdrjMdrjMdrjMdrjMdrjMdrjMdrjMdrjMdnjRLiF6lDPDmROdyJnDmUmgLVQ6PZw5HtRJpdOINoczY0CbqLSRaAPReqJ14YxJoLXhjCLQGqLVRKuoroNK7URtZFwZzpgMaiVaQbScmiwjaiE6NZxeAlpKtISomWgx0aJwejGoiUqNRA1EC4nqieqIFhDNp361VJpHNJeohihIFCA6hWgOkZ+ommg20SyiKqKZRDOIphNVEk0jqiAqDzvKQGVEU8OOctAUotKwowJUEnZMAxUTFRFNprpJ1M9HVEj9JhKdTDSBWp5ENJ66jyMqIBpLNIZoNA02imgkjTKCaDjRMBosn2go9csjyiXyEg0hGkw0iCiHhs4myqIxBxJ5iAbQ0G4iF/VzEmUSZRClEzmI0sJp00GpRPZw2gxQClEyGZOIEsmYQBRPFEd1NqJYMlqJLEQxVGcmiiaKojoTkZHIEE6dCdKHU6tAOiKVjAqVOBHTiPcSHdWa8CNU+pHoB6LDVPc9lb4j+ifRt0TfhO3VoK/D9tmgr6j0D6IviQ5R3RdU+pzoINFnVPcp0Sdk/DvRx0QfEf2NmvyVSh9S6S9U+jPRB0TvU92fiN4j47tE7xC9TfQWNXmTSm8QvR5OOQX0WjhlDuiPRAfI+CrRK0QvE71ETV4keoGMzxM9R/Qs0TPU5Gmip8j4JNETRH8gepzo99TyMSo9SrSf6BGqe5joITI+SPQA0f1E+4h6qOVeKt1HtIdoN9GucHIhKBxOngvqJgoR3Ut0D9HdRHcR7SS6M5yM85r/jka5g+h2qruN6FaiW4huJrqJ6EaiHUQ30GDX0yjXEV1LddcQXU20negq6nAlla4gupzoMqq7lEa5hOhiqruI6EKiC4i2EZ1PLc+jUhfRuUTnEJ1NtDWcVA86K5y0EHQm0RnhpEWgLUSnh5P8oM5wEg5jflo4aQxoM9Em6r6R+m0gWh9OagSto+5ridYQrSZaRdRB1E5Dt1H3lUSt4aQG0AoabDm1XEbUQnQq0VKiJdSvmWgxzWwRdW8iaqSWDUQLieqJ6ogWEM2nh66lmc0jmksPXUNDB+lGAaJTaLpz6EZ+GqWaaDbRLKKqcKIPNDOcKO4wI5wotvf0cOIZoMpwYh5oGjWpICoPJyIv4GVUmko0hYyl4cTNoJJw4tmg4nDiaaCicGInaHI4vhQ0ichHVEg0MRyP9zs/mUoTwnFB0ElE48NxYmuMIyoIx00BjQ3HBUBjwnE1oNFUN4poZDguFzSCWg4Px4kHGxaOE7GZTzSUuufRHXKJvDTYEKLBNNggohyibKKscJzw0kAiD405gMZ002AuGsVJlEn9MojSiRxEaUSpYVstyB62zQelhG0LQMlESUSJRAlE8dQhjjrYyBhLZCWyEMVQSzO1jCZjFJGJyEhkoJZ6aqkjo0qkEHEi5uuNXegUOBrb4DwS2+j8EfoH4DDwPWzfwfZP4FvgG+Br2L8C/oG6L1E+BHwBfA4chP0z4FPUfYLy34GPgY+Av1kXO/9qbXZ+CPwF+DPwAWzvg/8EvAe8i/I74LeBt4A3gTcspzpftwx3vgb+o6XFecCS7XwVeAX6ZYvX+RLwIvAC6p+H7TnLMuez0M9APw39lGWp80nLEucTlmbnHyyLnY+j7+8x3mPAo4Cvdz++HwEeBh6KWel8MKbN+UBMu/P+mA7nPqAH2Av7fcAe1O1G3S7YwkA3EALuNa9z3mNe77zbvNF5l3mTc6d5s/NO4HfAHcDtwG3AreY85y3gm4Gb0OdG8A7zqc4boK+Hvg64FvoajHU1xtqOsa6C7UrgCuBy4DLgUuAS9LsY410UPd15YfQM5wXRi53bom91nh99u/MsNct5plrgPIMXOLf4O/2n7+z0n+bf5N+8c5PfvImbNzk2VWzasGnnprc3+eIN0Rv96/0bdq73r/Ov8a/ducZ/v7KVLVLO8k3wr965yq9blbiqY5X69Sq+cxUvXsWHreIKW2Vb5VqlxnT42/ztO9v8rG1mW2dbqE13Uqjt/TaFtfFo8dP2NkdmKdi3sc1iK13pX+Fv3bnCv3zRMv9STHBJwWJ/887F/kUFjf6mnY3+hoKF/vqCOv+Cglr//J21/nkFNf65O2v8wYKA/xS0n1NQ7ffvrPbPLqjyz9pZ5Z9RMN0/HfbKggr/tJ0V/vKCqf6ynVP9UwpK/SV4eJZuS3elqzYxgenpmAlz8MnDHD7H+45DDh1zhBz7HWp8bJozTRkcm8qLZqTyFamnpV6YqsbaX7QrPvvg3NLYlBdT/pTyRYouwZcyeGgpS7Ylu5LVJPFsyZXVpRoXFhMPH609qzPZk10am8Rjk5xJSskXSXwrU7mLc8ZtINUkfpbPk5yl6kPaf5jTM84vYtXeih4Tm1URMs2cG+LnhLJmi29fVU3IcE6I+WvmBro5vyCo/f+0oUTxP0Rr5bO2bWMZkytCGbMDYXXHjozJwYpQp9A+n6Z7hWZoEvTOb1/V7g34TmZx78cdilOTHrG9aFNiY3lsbG+s4ovF5GOtTqsivnqtqs86fGxprMVpUcRXr0VN9llgEc+XEzOzujTW7DQr/kLzDLPiMxcWlfrMecNK/+U5d4nnpDt7O+bja357h1f7QynIV4miV1jFX3sHyuKzSisz7wkvagZa0I6rQxo7Ttzr//rF/90T+O1f9H+hT+pVzmSNyhnAFuB0oBM4DdgMbAI2AhuA9cA6YC2wBlgNrAI6gHZgJdAKrACWA8uAFuBUYCmwBGgGFgOLgCagEWgAFgL1QB2wAJgP1ALzgLlADRAEAsApwBzAD1QDs4FZQBUwE5gBTAcqgWlABVAOlAFTgSlAKVACFANFwGRgEuADCoGJwMnABOAkYDwwDigAxgJjgNHAKGAkMAIYDgwD8oGhQB6QC3iBIcBgYBCQA2QDWcBAwAMMANyAC3ACmUAGkA44gDQgFbADKUAykAQkAglAPBAH2IBYwApYgBjADEQDUYAJMAIGQA/oJvXiWwUUgAOMNXLY+FHgCPAj8ANwGPge+A74J/At8A3wNfAV8A/gS+AQ8AXwOXAQ+Az4FPgE+DvwMfAR8Dfgr8CHwF+APwMfAO8DfwLeA94F3gHeBt4C3gTeAF4HXgP+CBwAXgVeAV4GXgJeBF4AngeeA54FngGeBp4CngSeAP4APA78HngMeBTYDzwCPAw8BDwIPADcD+wDeoC9wH3AHmA3sAsIA91ACLgXuAe4G7gL2AncCfwOuAO4HbgNuBW4BbgZuAm4EdgB3ABcD1wHXAtcA1wNbAeuAq4ErgAuBy4DLgUuAS4GLgIuBC4AtgHnA+cBXcC5wDnA2cBW4CzWOKmTI/454p8j/jninyP+OeKfI/454p8j/jninyP+OeKfI/454p8j/jninyP+OeKftwE4AzjOAI4zgOMM4DgDOM4AjjOA4wzgOAM4zgCOM4DjDOA4AzjOAI4zgOMM4DgDOM4AjjOA4wzgOAM4zgCOM4DjDOA4AzjOAI4zgOMM4DgDOM4AjjOA4wzgiH+O+OeIf47Y54h9jtjniH2O2OeIfY7Y54h9jtjniP1/9zn8G7+C/+4J/MYv1t7eLzETl33BfPYfXiWwAAplbmRzdHJlYW0KZW5kb2JqCjEwIDAgb2JqCjw8Ci9UeXBlIC9Gb250RGVzY3JpcHRvcgovRm9udE5hbWUgL0FHWVlIQitDYWxpYnJpCi9GbGFncyAzMgovSXRhbGljQW5nbGUgMAovQXNjZW50IDc1MAovRGVzY2VudCAtMjUwCi9DYXBIZWlnaHQgNzUwCi9BdmdXaWR0aCA1MjEKL01heFdpZHRoIDE3NDMKL0ZvbnRXZWlnaHQgNDAwCi9YSGVpZ2h0IDI1MAovU3RlbVYgNTIKL0ZvbnRCQm94IFstNTAzIC0yNTAgMTI0MCA3NTBdCi9Gb250RmlsZTIgMTEgMCBSCj4+CmVuZG9iagoxMiAwIG9iagpbMCBbNTA3XSAzIFsyMjZdIDE4IFs1MzNdIDI0IFs2MTVdIDExNSBbNTY3XSAyNzIgWzQyM10gMjg2IFs0OThdIDM3MyBbNzk5IDUyNV0gMzgxIFs1MjddIDQxMCBbMzM1XSA0MzcgWzUyNV1dCmVuZG9iago4IDAgb2JqCjw8Ci9CYXNlRm9udCAvQUdZWUhCK0NhbGlicmkKL1N1YnR5cGUgL0NJREZvbnRUeXBlMgovVHlwZSAvRm9udAovQ0lEVG9HSURNYXAgL0lkZW50aXR5Ci9EVyAxMDAwCi9DSURTeXN0ZW1JbmZvIDkgMCBSCi9Gb250RGVzY3JpcHRvciAxMCAwIFIKL1cgMTIgMCBSCj4+CmVuZG9iago3IDAgb2JqCls4IDAgUl0KZW5kb2JqCjEzIDAgb2JqCjw8Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9MZW5ndGggMjk1Cj4+CnN0cmVhbQp4nF2Rz26DMAzG73mKHLtDBYECm4SQurJKHPZHo3sASAyLNEIU0gNvv8RpO62REuknf5/t2NGhqRslLY0+zMxbsHSQShhY5rPhQHsYpSIsoUJyeyF8+dRpEjlzuy4WpkYNMylLGn264GLNSjd7MffwQKJ3I8BINdLN16F13J61/oEJlKUxqSoqYHCJXjv91k1AI7RtG+Hi0q5b5/lTnFYNNEFmoRk+C1h0x8F0agRSxu5UtDy6UxFQ4i6eB1c/8O/OoDp16jhO4soTS5B2aaDHQDukIiiz3BNjMVKeBnoJlGHNS3Z2rXVtjRWZl7EiD+r6og7x9K41VtRBdsQST3ukApthz1mgfwX9d/1WbrPkZ2PcGHF1OD8/Oangtl09a+/y9xdoP5rUCmVuZHN0cmVhbQplbmRvYmoKNiAwIG9iago8PAovVHlwZSAvRm9udAovU3VidHlwZSAvVHlwZTAKL0Jhc2VGb250IC9BR1lZSEIrQ2FsaWJyaQovRW5jb2RpbmcgL0lkZW50aXR5LUgKL0Rlc2NlbmRhbnRGb250cyA3IDAgUgovVG9Vbmljb2RlIDEzIDAgUgo+PgplbmRvYmoKMTQgMCBvYmoKPDwKL1R5cGUgL0V4dEdTdGF0ZQovQk0gL05vcm1hbAovY2EgMQo+PgplbmRvYmoKMTUgMCBvYmoKPDwKL1R5cGUgL0V4dEdTdGF0ZQovQk0gL05vcm1hbAovQ0EgMQo+PgplbmRvYmoKMTggMCBvYmoKPDwKL0xlbmd0aDEgMTU2MDgKL0ZpbHRlciAvRmxhdGVEZWNvZGUKL0xlbmd0aCA3MDUyCj4+CnN0cmVhbQp4nNWad3xUxdrHZ86mJ5tsQhICC+yGJRFcqrRQJEsahAgkJIu7oWXTCBAgpNAEjCLFVRR7R6yosZwsKAEL2Dso9oZgufd6FbteLwr7/uY8+4Ryr/z1vp/73t397u83z5QzZ86ZOZMFIYUQZtEqTKJ4aumgc247PPZSRD4GFVULfQ1yaPCgEHIs0sOqljbbdzW8PxzpBiHCn6htmLtwzUHTSCEi+6MR59z6FbXVh8yom+xBmTV1Nb7q385doQuR8j7qj6hDwPyQKV+IVAvSfeoWNi8P/wROpA7Dl6V+cZVPrtHORToP6ZiFvuUNSV9mfIB0MdL2Rb6FNT1GD9+BNI4vVzYsbmoOWsV6Ibp+o/IbGmsauszt3U2ItDg0/7UwhTnlZhEuosJvCh+KGr1ITW+I9ZqIElpCuKZpYSYt7AsxMLhX9LkArUSr/kwutduFS9jF1ghxXMjnIrdomXYhgyrPtDM8Xh1NJONbYtzUCMaJMNEXGgGVQlM1g0GjFDT4ebDKKGW8IrcIcfwacfKrWMwXTbgGrTiXTeIasUd8JCrFWribxFZxr7hf6OJp8bJ4T/wvvo6vCF8o4kw70ecuQgSPBo8cvxd04OxORK5BqkuY/UQkaAl+e1rs2+PXBC3HOyKSRIxR16wdQPQneSx4VMtW6eAIldY2wCcYNX6I3HL8kePbThuDElEuZoiZYpaoED6cf7WoE/MwMgtEvVgoFhmpRcibi+9apOagVBVKKX+i1GLRABpFs2gRS/FugG8KpVTeEiPdIpbhvVysECvFBWKVWB36XmZEViFnpZFeDtaIC3FlLhIXG46VImvFJWIdrtoGsVFcesbUpZ3OLy4Tl+M6XyGu/FO/6ZTUZryvElfjfrhWXCeuFzfivrhF3Hpa9AYjfrPYIm7HPaPyrkPkdsOp3CfEC+JR8bB4RDxmjGUVRo1GhMel1hjDBozBKpzh2pN6TOO3rHO01uDc1bn5Q2e6HPGLT6qxNDSOquRalKRW6DqoVlafNhKbcQ7kT5wRpa4zzv9E9ORROVOUx+PWk0bmFiOl3OnRP/PXi9swA+/AtxpV5e6EJ3e74U+Ob+ksu9VI3yXuFvfgWmwzHCtF7oXfJu7D3H5AtIkH8T7hT3akD4uHjCuni3YRENvFDlzJx8RO0WHEz5T37+LbQ/FAZ2SX2C0exx3ylNiLleYZvDnyJGJ7QtHnjBilnxHPIq1KUeoF8SJWqFfEq+I1sV88j9Q+4/slpN4QB8Rb4j1phntTfIXvY+KN8C9EvBiP58hujPOtYjbe/4ev8O4iBWvxb8Flwd9ME0WtLJOvYVzvxKhcLiXWjc6XtImYsM+wuu8I/mqaCe177MPwuuN3Br9zla9f19zUuKRh8aKF9Qvmz6ubW1tTXTln9qyZM8q9HndZ6bSS4qlTJp9XNKlw4oSC/LzcnPGu7HHnjh0zelTWyBHDBw0c0L9vZkYfR29bWnKiJcEcGxMdFRkRjgeQFP3zHQUVdj2zQg/LdEycOEClHT4EfCcFKnQ7QgWnltHtFUYx+6klXShZe1pJF5V0dZaUFvtYMXZAf3u+w66/nuewd8jyEg/8pjyH164fMfxkw4dlGgkzEunpqGHPT6vLs+uywp6vFyyt8+dX5KG99tiYXEduTcyA/qI9JhY2Fk7v62hol33HScNoffNHt+Pxa1aH1U0Z+b5qvbjEk59nTU/3GjGRa7SlR+TqkUZb9nmqz+Iye3v/vf7LOyyissIZV+2o9s306CYfKvlN+X7/Bj3Rqfdz5On9Vn6RhlOu0fs78vJ1pwONFU3rPIDUwzMsDrv/F4HOO458c2rEF4pEZFh+EcqqU+wcJuSzF+gbeojzS09XfbmswyUqkdBbSzyUtotKa0C4Bjm9ulahcvZyTopb5bRyTmf1Cke6ulT5FaHP0ro0vbXSPqA/Rt/4ZOCDfLtuyqyorKpT6qvxO/LyaNzKPLorD8blC51rfvvgQSjvq8BJzFPDUOLRBzka9GRHDhVAwK6uwbxSj1ElVE1PztWx/wvV0gfl56l+2fP9FXnUQdWWo8SzSwwNHmofZrduHyqGCa/qh56ai4uSme/3VNfqtgprNe7PWrvHmq67vBg+r8NT41VXyWHR+x3C4dKNIxq1cG6nlebC6swjM6LsHs1q8qqrhYC9AF+OnLHIsOByGUl1RXPG2j3SKrgYjhIqodwp7SBhysidqLJMqmruRGu6N51eZ+iSNdSn8Aw96qS2LAh09omO86ddo9KqQ/3s+TV5J3XwlEbDQx0Mtfbv+6mpsQgdGDWi1OWcyFmmDMxcxDQ0Y4TUVUyz66LY7nHUOLwO3EOuYo86NzXWxvUtKnUUlZR7jKsdukvKTklRfhaldJGObE5oubgHC5xWvqxGeoKR7kxOPC27kLMdql9+f3W7MGWoW9naLg0TnnuZV5/q9Dr0SqcjXfVzQP/2KBGXXlaRi7lagOXOUeBz2C32Ar+vI9ha6W93ufwN+RV1ozEv/I7Car+j1DPWanR+mme1daU6dpIokkVlOWhKEzntDrmxpN0lN5aWe3ZZsG/fWOYJaFLLrcjxtvdBnmeXXQiXEdVUVAVVwq4SqqVpSEQZ5a27XEK0GrlhRsBIV3VIYcSiOCZFVYdGMQsdKNM4kAt/P1R1hFGOi0uHIRZFsVYq3TdUOgo5FpWzW+BBIoxMerULNcCumHBXlCvaFaeZNQypCgUQ2Y2y0VJsj5NmaW1Hm9OMcIdsbY92WXcZLU0LlWxFSRVr7Yyh56rYSQ3heHTi7hNn4C73bI8TaN/4Rokc9cJdmFaHewjPk3x7tbr/Vnnr/BVetXqIVNyr+EhdOsYJXXOMQ48j4vQYR02OHuvIUfFsFc+meISKR+LOl6kSF1stuv4KBxZizBiPsEqaaybVpL0jGCzzpL9uPeJNx1yaCco9erQTD7fwjEkoN0FRgfAEvbXKp/oh3B5VNzKjsMqLeckNokihHo0WokMtoESBUUfNN1Sqwr3mcxgWYSwdrV7d61QH9czzGvPVoouJjtF6RCa1GZ6pDjTI609ynGMsPpjrMRkblESjb6LUQxErkjiYlwYpMg49r3Igq6rCTvdIKeYyPSxirBSpwZofllljEGMNZQp1WqaMWHOMHj0QDeKjfOxAteaEZ0R6vdR5I7UhVADHtuix6FHmSUMZqoDRQVah6gs+G9BVVfRp1UxJh5jmWI6lU3XaaCkS2bo5o9CHpxvVj0XEkcWVo9QiGBtq4zmKRqozj8O4Y0noCG5zrEg/6YW1Qz391P0nrLswUYXXf3pAn+Ec0D/q9KjZCPv9UeZ/X4HGK8rcqUZQy6hSTwWouuGM+82erx6Vjknt2hSnodJQ/yQHniBahgIbHROmT7q92qtKocvFxlr2p4XkSYXUY9po3G8ZwykZStHF9OtzT03WdSYLFNgMZgykPQRORa21uFfmW/V63JlcRF0Ru99ucYx2qC+j8gRFBS5S57TA7Y+7Tk2a1iq7pxI3OxosqPAX+NUWtcoXGrbQkfRFzlOaxLyQuHnQkDodvbXYXuG1V2BrKks86elWzEaovRb7VIdPPQqK6XyKy42tis+vbnGBnYrXqkfiwVTrq3Gk4wmiqxWIRl/1MSw0bYTV73f4dWPeFqAwms/EtCtUgk+D0+GrUVvoWrWDrjHqFqC7xuio1qz5DszlGoSNscTAYemrVF9VfrVBn1XhxEgk+pP89lF+LMGz8PQIy6yaXoFHlXoi2Y1L7bMihUEoVCkvGqKC0RmqIE0B1ZuFzvZZkRknIsZnsZMKRxmtomfTPHoxFzHmkzJLnLrWNQuZ6uTltHIPr1MmlV2I4XXhrrKq2nZdK/OELo9Rv1BVtfIFo2qIGM+Q0PzqfNrwc2imFWP6p3H8wSXE8SbTgfB4YRKRYpSYLKaIG/R1Ts8TeBJME6litHz00ZS8vKgBkU/JXPWTmSzDo0zKXFdCmGbe2b17tmPn8IhNpsTCDjlgR3bkJk0T2ccOHts36NjBI0mjBh2Rgz45fPCw5Yd9iaMGDT389uEhg62u5O7mnfWoOtyxs364KWJTvSkxW9V3Rddnu7TITfVoJC3b2X2fc98g5z4nmnEOHuKViemJBsnxWmRkcoSj90Bt+FmZI4YOPWecNnxYpqN3vGbEho0YOc409JxemimZI+M0lZamA3+Um6Yei9DWOLKnDw3v1T0h2RwRrvVISxowNsNSOiNj7MCekabICFN4VGTfkTm9i+rze38YmdgzJbVnUlRUUs/UlJ6Jkcc+Co8/+mN4/O+5YfW/X2uKGDMzu4/pxpgoLSwioqNXWrezx6QXTk/oYgmL7WJJTI2KTEqM65s389j6lB6qjR4pKdTWscnYW6jfGyNGHy77MuXhOQljfxHRUcZft49/veo1pe8VLpv6+9FjrdHfRI0Q6ldPjf/8VT9iqt88Y7b+fvTo1uhvTvxyGXqFhcWf9NfyfkP2dL5V6TDRKixiLNrUoIPEBiGSRvT5OtSrSFGufjUNU7+0NgPyUvRAirwm4sXmkDfhD4stIR+GMgdCPhy30LchHyF6yDBRZvyq1STsoW8fqBWL8bd9M9yy0G9edZ35zaLG+LVL/VroA/NEvVhh5C4yfqnyIV2PMtViIKJ5KGc3fl9UrbWgRI1IF+M735OEU+QadeaJSqO1aSgxFyXrjdaL0UKBGH3GGqPFYLyH4HiDjfeZyk5H6+qXzHnGGdpDtc5UQ4208Qqmqd/M//XVHm0aX6q9pL0gsoRNezGkn4gs7UPh1j6Avgd9P6TvQt+Bvg19C3oA+iZ0D/Qp6JPQJ4RbhGkfiWGgDJg6XTW4G7wNwsUCtCRFLOpLkaw9I/JANWgG14JwlH0KeXejRSns2iU7otPkJCzCa9lczOYiNq1sLmSzhs1qNqvYXMBmJZsVbJazWcZmKZsWNs1smtgsYdPAZjGbRWwWsqlns4DNfDbz2NSxmcumlk0Nm2o2VWwq2fjYVLCZw2Y2m1lsZrKZwaacjZeNh835bKazcbMpY1PKZhqbEjbFbKaymcJmMpvz2BSxmcSmkM1ENhPYFLDJZ5PHJpdNDpvxbFxsstmMY3Mum7FsxrAZzWYUmyw2I9mMYDOczTA2Q9mcw2YIm8FsBrEZyGYAm/5snGzOZtOPTV82Z7HJZJPBpg8bB5vebNLZ2NnY2PRi05NNDzZWNt3ZdGOTxqYrm1Q2KWyS2XRhk8QmkY2FTQKbeDZmNnFsYtnEsIlmE8Umkk0Em3A2YWxMbDQ2ko0IGRlkc5zNMTZ/sPmdzVE2/2TzG5t/sPmVzS9sfmbzE5sf2fzA5ns237H5ls0RNt+w+ZrN39l8xeZvbP7K5i9svmTzBZvP2XzG5jCbQ2w+ZXOQzSdsPmbzEZsP2XzA5n0277F5l807bN5m8xabA2zeZPMGm/1s9rF5nc1rbF5l8wqbl9m8xOZFNi+weZ7Nc2yeZfMMm6fZ7GWzh81TbJ5k8wSbx9nsZrOLTQebnWweY/Momx1strMJsGlno7N5hM3DbB5i8yCbNjYPsLmfzX1strG5l809bO5mcxebO9ncwWYrm9vZbGFzG5tb2dzC5mY2N7G5kc0NbK5ncx2ba9lcw+ZqNlex2czmSjZXsNnE5nI2l7Hxs7mUzUY2G9isZ7OODW97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97JG97ZCMb3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3v9I3vZI3vZI3vZI3u1I3u1I3u1I3u1I3u1I3u1I3u1I3u1I3u3I3O3KdGiXBHqNs2HPHOiVArmYUhcFeo2GtFLqQpI1gV5xkNWUWkVyAclKkhWBnuMhywM9cyHLSJaStFBeM6WaSBopuCTQMwfSQLKYZBEVWUhST7Ig0CMfMp9kHkkdyVyS2kCPPEgNpapJqkgqSXwkFSRzSGZTvVmUmkkyg6ScxEviITmfZDqJm6SMpJRkGkkJSTHJVJIpJJNJziMpIpkUsBZCCkkmBqyTIBNICgLWIkh+wHoeJI8klySH8sZTPRdJNtUbR3IuyVgqOYZkNFUfRZJFMpJkBMlwamwYyVBq5RySISSDqbFBJAOp3gCS/iROkrNJ+pH0JTmLms4kyaA2+5A4SHpT0+kkdqpnI+lF0pOkB4mVpHug+xRIN5K0QPepkK4kqRRMIUmmYBeSJJJEyrOQJFAwnsRMEkd5sSQxJNGUF0USSRIR6FYMCQ90K4GEkZgoqFFKkghDZJDkuFFEHqPUHyS/kxylvH9S6jeSf5D8SvJLIK0M8nMgrRTyE6V+JPmB5HvK+45S35IcIfmG8r4m+TsFvyL5G8lfSf5CRb6k1BeU+pxSn5EcJjlEeZ+SHKTgJyQfk3xE8iEV+YBS75O8F+h6PuTdQNfpkHdI3qbgWyQHSN4keYOK7CfZR8HXSV4jeZXkFSryMslLFHyR5AWS50meI3mWSj5DqadJ9pLsobynSJ6k4BMkj5PsJtlF0kEld1LqMZJHSXaQbA+kZkMCgdQZkHYSneQRkodJHiJ5kKSN5IFAKtZreT+1ch/JNsq7l+QekrtJ7iK5k+QOkq0kt1NjW6iV20hupbxbSG4muYnkRqpwA6WuJ7mO5FrKu4ZauZrkKsrbTHIlyRUkm0gup5KXUcpPcinJRpINJOsDKT7IukBKJeQSkrWBlFrIxSQXBVLckNZAChZjeWEgZQRkDclqqr6K6l1AsjKQUg1ZQdWXkywjWUrSQtJM0kRNN1L1JSQNgZQqyGJqbBGVXEhST7KAZD7JPKpXRzKXelZL1WtIqqlkFUkliY+kgmQOyWw66VnUs5kkM+iky6lpLx3IQ3I+dXc6HchNrZSRlJJMIykJJLsgxYFkdYSpgWR1e08JJK+FTA4kD4CcR0WKSCYFkrEvkIWUmkgygYIFgeQ1kPxA8gZIXiD5QkhuILkVkhNIKoCMJ3GRZJOMCyTh+S7PpdTYQKIXMoZkdCBR3RqjSLICiRMgIwOJHsiIQGI5ZDjlDSMZGkjsDzmHSg4JJKoTGxxIVHNzEMlAqj6AjtCfxEmNnU3SjxrrS3IWSSZJRiBRjVIfEge12ZvaTKfG7NSKjaQX1etJ0oPEStKdpFvAMguSFrDMhnQNWOZAUklSSJJJupAkUYVEqmChYAJJPImZJI5KxlLJGApGk0SRRJJEUMlwKhlGQROJRiJJhCuYUGlTHE+osh1LqLb9Af87OAr+idhviP0D/Ap+AT8j/hP4EXk/IP09+A58C44g/g34Gnl/R/or8DfwV/CX+Lm2L+PrbF+Az8Fn4DBih6CfgoPgE6Q/hn4EPgQfgPfNC2zvmYfY3oW+Y663vW3OtL0FDsC/aXba3gD7wT7kv47Ya+aFtlfhX4F/Gf4l83zbi+Z5thfMdbbnzXNtz6Hus2jvGfA0cAX34nsPeAo8GbfE9kRco+3xuCbb7rhm2y7QAXYi/hh4FHk7kLcdsQBoBzp4JHaF7eHYlbaHYlfZHoxdbWuLXWN7ANwP7gPbwL3gntgBtruhd4E7UecO6NbYBbbb4bfA3wZuhb8Fbd2Mtm5CWzcidgO4HlwHrgXXgKtR7yq0tzlmiu3KmKm2K2Lm2jbF3GO7PGabbZ0pw3aJKcu2VmbZLna3ui9qa3Vf6F7tXtO22h27Wsautq4uWn3B6rbVH612JUXErHKvdF/QttK9wr3MvbxtmXu3tl7UautcY91L21rcYS3JLc0tpp9bZFuLzGuRg1ukJlosLfYWU1yzu9Hd1NboFo3Fja2NemPYGL3xUKMmGmVMR3Dv9kZrrwKoa1Wj2VKwxL3Y3dC22L2odqF7Pjo4L2uuu65trrs2q9pd01btrsqqdPuyKtxzsma5Z7fNcs/MKnfPaCt3e7M87vNRfnpWmdvdVuYuzSpxT2srcU/NmuKegvjkrCL3eW1F7klZE92FbRPdE7IK3Pk4edHD0sPew2RRHZjSAz0RVpkz2OqyHrJ+bw0TVt2612pKSuhu6671S+gmc6d2k4u7Xdjtym6mhLT9aZorrV//goSu+7t+2vW7rmFdXF37DSwQqZZUe6opRZ1b6uSyAkOz80iHDDfO1ZbqyCxISJEJKbYULf+7FLlemKRdSiEtEFMUyuyQKbYC05PGP8yFCyk3izJnUUeUmFakRxXP0OVGPaNUfbtKyvWIjbpwl8/wtEt5hdf4f0R6svqPYEZ63aZNomdOkd6z1BMwbd3aM8dbpLcq73IZPqi8QBGvc3ZTS5PT4zpXJB5K/D7RlLLHst+iJSTIhIRgguZKQOcT4m3xmvoKxptc8UNGFiSYbWZNfQXNplSXGRF1fmfFFZcVJMTaYjV3duzUWM0Vm51b4IodMLjgX85zuzpPOrKzeTa+Zjc1O40PUl7ZopJOFVWfpmak1bvFSAvnGV9UDDKnCa9mDjafudb/95f8T3fgv/9F//tufFC7RFRra8HF4CLQCi4Ea8BqsApcAFaCFWA5WAaWghbQDJrAEtAAFoNFYCGoBwvAfDAP1IG5oBbUgGpQBSqBD1SAOWA2mAVmghmgHHiBB5wPpgM3KAOlYBooAcVgKpgCJoPzQBGYBArBRDABFIB8kAdyQQ4YD1wgG4wD54KxYAwYDUaBLDASjADDwTAwFJwDhoDBYBAYCAaA/sAJzgb9QF9wFsgEGaAPcIDeIB3YgQ30Aj1BD2AF3UE3kAa6glSQApJBF5AEEoEFJIB4YAZxIBbEgGgQBSJBBAgHYeOD+DYBDUggRLVETB4Hx8Af4HdwFPwT/Ab+AX4Fv4CfwU/gR/AD+B58B74FR8A34Gvwd/AV+Bv4K/gL+BJ8AT4Hn4HD4BD4FBwEn4CPwUfgQ/ABeB+8B94F74C3wVvgAHgTvAH2g33gdfAaeBW8Al4GL4EXwQvgefAceBY8A54Ge8Ee8BR4EjwBHge7wS7QAXaCx8CjYAfYDgKgHejgEfAweAg8CNrAA+B+cB/YBu4F94C7wV3gTnAH2ApuB1vAbeBWcAu4GdwEbgQ3gOvBdeBacA24GlwFNoMrwRVgE7gcXAb84FKwEWwA68E6UT2+VWL+S8x/ifkvMf8l5r/E/JeY/xLzX2L+S8x/ifkvMf8l5r/E/JeY/xLzX2L+S8x/2QiwBkisARJrgMQaILEGSKwBEmuAxBogsQZIrAESa4DEGiCxBkisARJrgMQaILEGSKwBEmuAxBogsQZIrAESa4DEGiCxBkisARJrgMQaILEGSKwBEmuAxBogMf8l5r/E/JeY+xJzX2LuS8x9ibkvMfcl5r7E3JeY+xJz/z+9Dv+Xv7z/6Q78l79EU9NJGzP1SpszW/wP9+ZQTwplbmRzdHJlYW0KZW5kb2JqCjE3IDAgb2JqCjw8Ci9UeXBlIC9Gb250RGVzY3JpcHRvcgovRm9udE5hbWUgL0FBQUFBSitDYWxpYnJpCi9GbGFncyAzMgovSXRhbGljQW5nbGUgMAovQXNjZW50IDc1MAovRGVzY2VudCAtMjUwCi9DYXBIZWlnaHQgNzUwCi9BdmdXaWR0aCA1MjEKL01heFdpZHRoIDE3NDMKL0ZvbnRXZWlnaHQgNDAwCi9YSGVpZ2h0IDI1MAovU3RlbVYgNTIKL0ZvbnRCQm94IFstNTAzIC0yNTAgMTI0MCA3NTBdCi9Gb250RmlsZTIgMTggMCBSCj4+CmVuZG9iagoxOSAwIG9iagpbMjI2XQplbmRvYmoKMTYgMCBvYmoKPDwKL1R5cGUgL0ZvbnQKL1N1YnR5cGUgL1RydWVUeXBlCi9CYXNlRm9udCAvQUFBQUFKK0NhbGlicmkKL0VuY29kaW5nIC9XaW5BbnNpRW5jb2RpbmcKL0ZvbnREZXNjcmlwdG9yIDE3IDAgUgovRmlyc3RDaGFyIDMyCi9MYXN0Q2hhciAzMgovV2lkdGhzIDE5IDAgUgo+PgplbmRvYmoKNSAwIG9iago8PAovRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDE2NAo+PgpzdHJlYW0KeJyNjs0KwkAMhO95ihxVcJvsj7sLZcFiLXhTF3oQb2pvQuv7g6mI7dGEIcxAmK8HUjROCJ6R0EWnjMZgWUWNwx3aFTyhylA0ZybsXkA47tB9Ep6SUwPFnpED5gdo65WN6J1R0WK+waUkYk3kjXSJOBD7HTFTsiVx5cSKuE7r0ftNYi03btMV8wHqDEfo/2X9Ic7I9JfMCJl8z8gWuJw63vPXN+AKZW5kc3RyZWFtCmVuZG9iago0IDAgb2JqCjw8Ci9UeXBlIC9QYWdlCi9NZWRpYUJveCBbMCAwIDU5NS4zMiA4NDEuOTJdCi9SZXNvdXJjZXMgPDwKL0ZvbnQgPDwKL0YxIDYgMCBSCi9GMiAxNiAwIFIKPj4KL0V4dEdTdGF0ZSA8PAovR1MxMCAxNCAwIFIKL0dTMTEgMTUgMCBSCj4+Cj4+Ci9Db250ZW50cyA1IDAgUgovR3JvdXAgPDwKL1R5cGUgL0dyb3VwCi9TIC9UcmFuc3BhcmVuY3kKL0NTIC9EZXZpY2VSR0IKPj4KL1BhcmVudCAyIDAgUgo+PgplbmRvYmoKMjAgMCBvYmoKPDwKL0Rpc3BsYXlEb2NUaXRsZSB0cnVlCj4+CmVuZG9iagoyIDAgb2JqCjw8Ci9UeXBlIC9QYWdlcwovS2lkcyBbNCAwIFJdCi9Db3VudCAxCj4+CmVuZG9iagoxIDAgb2JqCjw8Ci9UeXBlIC9DYXRhbG9nCi9QYWdlcyAyIDAgUgovTGFuZyAoaHIpCi9WaWV3ZXJQcmVmZXJlbmNlcyAyMCAwIFIKPj4KZW5kb2JqCjMgMCBvYmoKPDwKL0F1dGhvciAoVGFyaWsgS3VrdWxqYWMpCi9DcmVhdG9yIDxGRUZGMDA0RDAwNjkwMDYzMDA3MjAwNkYwMDczMDA2RjAwNjYwMDc0MDBBRTAwMjAwMDU3MDA2RjAwNzIwMDY0MDAyMDAwNjYwMDZGMDA3MjAwMjAwMDREMDA2OTAwNjMwMDcyMDA2RjAwNzMwMDZGMDA2NjAwNzQwMDIwMDAzMzAwMzYwMDM1PgovQ3JlYXRpb25EYXRlIChEOjIwMjUwNTI5MTY1NzU0KzAyJzAwJykKL1Byb2R1Y2VyIChpTG92ZVBERikKL01vZERhdGUgKEQ6MjAyNTA1MjkxNDU4NTNaKQo+PgplbmRvYmoKMjEgMCBvYmoKPDwKL1NpemUgMjIKL1Jvb3QgMSAwIFIKL0luZm8gMyAwIFIKL0lEIFs8MjREQ0I3OTM1RDk2MjE0NTg2Mzg5OTY1MjI4NEE0NzM+IDxEQkQ5NTZGOEYxQ0NEMTg4MTQ3QzE5QkU4RjdGMTBBRD5dCi9UeXBlIC9YUmVmCi9XIFsxIDIgMl0KL0ZpbHRlciAvRmxhdGVEZWNvZGUKL0luZGV4IFswIDIyXQovTGVuZ3RoIDg2Cj4+CnN0cmVhbQp4nGNgYPj/n9FLjoGB0fMpkPAqARIeR4GE+00goWkFJNQ3gwhuIMHADyRUJ4BYkUBCrRckcQqk7giI+AvSpgck3KSBhJYZiCsBMnknkPAGagMA4WYQSgplbmRzdHJlYW0KZW5kb2JqCnN0YXJ0eHJlZgoxOTM0NAolJUVPRgo=";
        private const string PngBase64 = "iVBORw0KGgoAAAANSUhEUgAAAjMAAAIFCAMAAAAQr4xAAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAA8UExURf///3DN5Kzf6nqjzAB4rgBJYgG85GWUxQBpkwCT0fH2+d7p863G38XZ6Za21kHG5AGl2gCGwUR5i3DfzC5rUXgAABDiSURBVHja7J2Jdqu4FgUTkxsnIGE7//+x7TkgNBwNuCNRdfut9bpvjA2U9zmSgLy9AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvJBBq7H7OfPvxuX/dqMaeg4N2HQZ909XTM7mIA5M6fXo1GUizh5v4BYwah/25enNqNFm8wkTIcxDm4HjtuGIGWOFubEnbDYbMV//UvkZsWaDxvz8y4IShTFkDfjQ+39F+FFYs5HOt5uc9q9/X7/8i25wfjTHcwNlSd3L0peTKGs6oqb5kNn7fYk3h6hpnEvIfIkhauDSyXzFQdRsfLj085WCaADF0W1TmY+vRKhPW1Xm++PBGtb8MC3cnjKH79PHlNLaIE17yhy/DWk+SktDJ9wS/fD+eXbm+8OkqDVI09Qg+/3weVbGDJri1iBNO4Vp9/55dcYmTaQ2SLONlNmdY+b4/QppKE8NKfNwxi5NnDaMnjagzNSZ7w+kgcCQaXd25nPijEuaUtb8MCPcgjKHmTOnjwLW+JYROOrVD5muMTNxZnVpRg573c3MPWamznikKWINg6fqlVk6s7o0tDQ1NzOP0iR2JsYaWpr2lJnEzNwZ9+CpkDRcg1VvZXI6s3LSMEtTdWW6lab7epNQmo9saahONceMw5m1pWHsVHHMHFzOrCsNY6cKldEBZ/x9cL40tMHVVqanM8fvuOokt4agaYRHzDzaGYszIWkyg4YlhFpj5umMpTitmzQETWXsRM6UkoagaSRm5u2MtTiF+uA8aQiaOruZkDOnNaVh6FRlzEycsRanUtIQNBtyZlVpmAyuZz7vV5mpM8eXS8OqU40xI3Am2AenS8PydlUDbYszjuJUShq64Npj5uHMRBln0KwnzQ9no77SNMsZpzOntaShOFXUAVudcRanQtJQnBp05vhyafacj+raGakz4Zbmg+LULtrtzP8gDdN61ZUmuTPf6zjDtF51pclw5tPjzKlE0jDabs+ZY5Y0Kc7Q0NTWzswn9fzOrCMNDU0l7YwzZ/zSFKhOXK1XvzPvMc6sIQ0zNJW0MxNnDi+WhguvtubMqbg0NMGVtMAeZ7KliQ0anGndmXxpGDjV3gIvmuCgNB+FpWHg9NfZLaSJdSZbGpypMmemzhzKSxPlDCtOtQ2bUpw5FZWGCZoWcmZtaVilrDFn/E2wd3m7gDRM6lXvTELQfBcMGpxpw5lg0HyXCxqcqdAZW3E6ZkuDM1tzJixNzm3cOFO9M4ekoCklDc7U6Exa0ORIgzMVzs+Ei1O4Dc542h7OVO/MIU2aU7I0zOlV74w9aI7rBQ1rB/U7c3h1dWKNsiJinFlPGq6FqAkdUZwE1Sn1+fY8TqR+Zw4rSSNwhms7a5mgMZxxBI2kOp0yixPXkNfqTHrQJP2eJ6Znahw4CYMmW5qgM5yTap05fL6ypWGo3UAT7AwaQUuT8JuVGTa10NDkBE28NAybqnRGHDS50nidoQWuuaFxBk12S+NzhtWmqhsaZ9DkDp58zrByUHdxcgbNZ/HqxIxeI864gyZTGrcztDOVNTSFq9MpwRlmZ6oPmsOrpGGk3YwznuqU1Qe7nKE0NVCcDq+RhtLUUtCsJI0jZxg11edMVHXKmdujNDUzrWdx5iXSsD7ZVtAcVpHG5gwxU2cXHClNcktjc4YOuJmg8VUnSdKEpeEJ5M0FzSrSEDNtB02mNCeZM8RMU0FzKC/NwhliprGgWVUaupkmg2YFaYiZloImXprPBGnmzhAzNQaNXlUajzNMATcbNAFp4h87PYsZpoCRJpw005z54Vqr+tvgFGk+06ThboNWgiZJmrhfQziJGSpTu9XJPyMcKQ2Vqbmxk8OarPpkd4bK1HZLk1mfFs5cbrelMjXe0gSl+ZRKc3eGZmYL0uREzWnuDBPAzbU0K0TNyXCG/rcBtCRpglFzDEtzVYb+dztJE4yasDQXZ1CmwcGTO2nSrTk9lenof5uUJrk+ua25O4MyG5RGYM3RKc3XF8pssKdJt+biDMo0LU2WNVZtPr5of9ue3PNK834Ia7Pw5siFeQ0mjSFNtjUXb568M/u7haTxSiPV5sZhRyuzkaYmYI1Qm8OBkNlS1ISsCWpzFuadkNnUTI3Amos3B4cvZ2HedwPKbK0VFkhzF+fizvXPldt/3hEym+xqpNos2e3oZLba1aRZs6MsbbpARWtzfoHGGKzZRQiz05QlrJF5s7sKQ8Zs1hq9i/HmrsslYjCGsDF5yPR+/zNlwJjNW+PQxiETwsB17O0sUjsSBjxxo/35gi9g8eYszqANdfTZlqHHF/Cqc5bnCYcDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgRfSyfxK3Vd1+xn/sftBnhtgXVffIrcsTCpVSoxjlPCb95Zj5tnX+u/MhdR6i6wcp/BTw/rrN3488ROzp40Nr2VNgB9XtL3QqYheGsTuTttf6ti/31/bXf007gMNtU2qQHdHxtqMRdINVvfOWZJvqzrtpOQl9yiEP7p+xzSF6b2+v78bguZhsWv6rlZ8vGuN/xYKav93vv0ZvSj8/upZ+MWJRFmFitzQuToH6/btS0vSLbap9Ot3o02ZqY6elH3CMf83ztb9vOMzfvxtSldl3oQPaJR680fwyj0mnYJ4n02NeSpqpIbfjOO6z8Fgz23In3IFh9lWM2+vJay+66VAlkCiz38t/MvJsz0928nmY7Zr2JlkSlk1mOuOOAx2IYsmr4r4qhjOzqhshTT/7DJ0stTOdyXBvdgLUvrQ0895lLOOMIw4WfZKODsLYTsRwZr4tuTRK+rGzlJnVJl3qW6tEX+dkZco5Y40DJRooBF8WU1RMZ/oxZUtiZbJawdmWdW7UD46P1OX+qrZ+3K/kjEUaLTNLoJpOdsaURpdVRttGk1JG7Ylk/6Z8Y7Ccr5wkSRfOyPfY96UxhzBx1UlZRgbJzsRL08uVMbY9qstvFhHj2efApi6zh+Z00FMNlfRFlZ8N05lOusvD8mObwyIlnsYS5L3qU52JlWaujP/HZ8MyNZRqGUbRDKQ5l6Ochy9HGr0POhO1deNTD+7jGfX5lbRfkjkTExyRho2JnbpfvohKPFqOkBLMHab2vzZnoo2cblO5jr1y/lREXyk7KTZnYqIjLpS6Uk3DmNh+TPfs8UKV2BIEpkgL5YzxDVGOE3/eqI75GqmI1RmRM2bSqELKvO0TFkZCb6uTT6rHmcQRdz/u13BmEiHKkT96/ubB91CRM4dhZ6QTXbEj82LOdMlJrxY7nNxHCief1nJmVpkWiyDiw9AZKzkq2RmRNEPsZE6p6da+S5ZPy5xJ6oP1XuJM/JZ7qzNqEStaXl0nzgxGDxYcPjmdMQ6AbUPRyqyRM7HyDUJnEk6tYzFjpZyZLifr6DZv6oxZUkN77namD0kTr8xfcMaXM/OYVuln9rx/3crOLCrTojr1YmfMoho4l4MnzebfG1OaeaLJ6v8KtalozgwqffA0H8cPazujrA2vljo/d2YhjU51xpBm7D2zarKWcY0euGTODG/J0szyvRv6bt1+xnWhk7Q6KfPH5ufaK43XGY80Scr8+X5mME992pLB+Yj36+aMtTKZcwm+N1o4Y3Zjnk7Y74xTmqFLahf/QG0K5IxxBVGfsNnbZMm6zmjnwRdWp6Uz5iVsbmkCzjjk0GnKVJAzZivbR5/V20da1xnfJbhKVFwtziyGT0OiM1ZpUpWpoJ8xI0O21rv0rGg/Y64dOCuT+VncxdXmjHT4FHTG0rkkK/P3x03LCRvJ9i1NUMmcWayUaO/R15KTY3XGnF9xdMJhZxbSpCvz5+dnBosCkRcQ3X++oDOLddXQzSGS6qQcm5AMnwTOmDMxSdfp1NPPmN1gePBkG58Xc6ZfXr8xBlKwF1QnlzNvgoUEiTOem0Ii74z54+tNv0OImNsvrPe6FOln+ss9oot1Px0MeUF1cjpjnmzL60XOOKWJvVm1kpwxPPCfZPs4y+PMXskYx8XdyZeIkty2qIINmduZ8PBJ5oxDmuj7m+voZ6Kk6e2R5HMm774LJThjs0tpdKQzweGT0Bnr1UTx9aWOcdPyuAkvOpsOW9dwRosqk9nKWvsnnzPPBxQ4rJM6Y5Em4bRXMT9j218d0/+u5Yyeb1e4nmQ/Ucq/GWMhQac5s5Am5erHavqZRR8suVlava3pzPUj9CqlLuhoZ7zDJ7kzRlwnXTBbwXqTS5ohVALmpaK0M/dnWcyuEx8GPTj/p/wfPuSM7zqsCGcyrtyuMWeMELF1BZ71zLLOPO4Fm828ZN2zG3TG0wnHOOM+ug32M4ujtjzuvusmyjnTjer5bC6V0wpFOuO+Duv/ckZVkDNGPitveus3sTOd5M/1BvXLHcW9szONEW+Id8a5kFB9zqzXz4Sk8Y7GfWsHgwjzDnXH3VOJ1UnkjOM6rM05E5Mz3sGT/5KJotfP5FYmr/DeIbv1Oqzqa9O4Zs4Y37Tp3wcuzVrBmaHLccZ5+5p/Oc22+kTOBPbK8eCv0EC8vDN97mi9T3HGNnyinwkdPuvgKXiJTdHr9PIr0+KQi52xPDsu0Zmuydpk/SYYfXAvW40qnjPTa4K1HNd0cMypNIdP9c/PFLzHXzKNrpZDpv4FzkzMVYmqzXYv6utvPlTypc6Uev5MkWeJWJ4/MwgOmfYtGazmjEp9ueP6q7iS4bzo7gXOjPvcqr7cUNwziyzPaAkfvvkiwiC5iq9wP/P7lrFftllpValtxn/t3clO6zAUANBKWSDZcf7/c3nQvkKm1r42WZ0jgcSCNMP1nPqedcAviJk58N3Lt09xqs/nsX63tv6q1oOnmgXvsfVMtGU6b51au6Yn+zpfEDNls/AWrmvSZg/GmiOlskxH11uz9LJ8NFbOY2Om9FRS5WjA3T6cKdP7mcK/GDdtV+q+tmgtOddOpp+PPKf7Zq+nysFer6mhJJy+EH27ImbiLdNp6xR4lEdBc0E907oV9Pme0sclv35H6V+XW3X7jidhz0v9yP5MT8u0O/cSL/556oqZaD2T+racz8Nm0g+7gx+5rZS9uAsj65nSO3A4yJYTepT72vaKmOkMmnnY8svcPOycW0JmZMz0tUy7LsE97mKPctcTvqJtunWm0Bm0ALPK+lV7VXNLIRsXM7+eUzjlS9qlkgsW/23QXFLPfJWb+MrJum5O0fBbD/Nrr2obo/MtFjNLNCtbx5TWbkfP8KNc3/N8TT2z/QpyeJntFkwuuM2OUGpvX8tGTePqmTJk6nweFTPr+Z7UEK1TZ97GYBLT+aB/1HakZT8pVF+QWzJXbluUOTr2eUZfVzKybaeoo/bKTcO4PGiJ8f8M29TVNP1UW/NSkXf5PoWTXrTR77cNed6u92mVf3IRp3XLFk2R0Zn08NmmLK0XfXDDpvpL+fmgfBsg5Xsm9Vov1gjS62N95bg/nypOj3+syg/xnUK85JpCsT7px9+Bue9/lfLUn/v7ETTPN4Aep5djzcQyTXUZkHb3Yaj05qfpQL9+/cV5XizlAR/6HXqjHt3uBXcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAsE8t/ib5Gh87OAAAAABJRU5ErkJggg==";

        public static void SeedData(ITapplyDbContext dbContext)
        {
            dbContext.Database.EnsureCreated();

            if (dbContext.Roles.Any())
            {
                return;
            }

            SeedRoles(dbContext);
            SeedSkills(dbContext);
            SeedLocations(dbContext);
            SeedUsersAndProfiles(dbContext);
            SeedJobPostings(dbContext);
            SeedJunctionTables(dbContext);
            SeedApplications(dbContext);
            SeedRemainingData(dbContext);
        }

        private static void SeedRoles(ITapplyDbContext dbContext)
        {
            dbContext.Roles.AddRange(
                new Role { Name = "Administrator" },
                new Role { Name = "Candidate" },
                new Role { Name = "Employer" }
            );
            dbContext.SaveChanges();
        }

        private static void SeedSkills(ITapplyDbContext dbContext)
        {
            var skills = new[]
            {
                "C#", "Java", "Python", "Go", ".NET Core", "ASP.NET", "Node.js", "JavaScript", "TypeScript",
                "React", "Angular", "Vue.js", "HTML", "CSS", "SQL", "NoSQL", "MongoDB", "PostgreSQL", "MySQL",
                "Redis", "GraphQL", "Docker", "Kubernetes", "Terraform", "Ansible", "Jenkins", "GitLab CI",
                "GitHub Actions", "AWS", "Azure", "Google Cloud Platform (GCP)", "DevOps", "CI/CD", "Git",
                "Agile", "Scrum", "Project Management", "UI/UX Design", "Figma", "Sketch", "Mobile Development",
                "iOS", "Android", "Swift", "Kotlin", "Flutter", "React Native", "Machine Learning", "Deep Learning",
                "Data Science", "Big Data", "Apache Spark", "Hadoop", "Pandas", "Quality Assurance", "Cybersecurity"
            };

            dbContext.Skills.AddRange(skills.Select(s => new Skill { Name = s }));
            dbContext.SaveChanges();
        }

        private static void SeedLocations(ITapplyDbContext dbContext)
        {
            dbContext.Locations.AddRange(
                new Location { City = "Sarajevo", Country = "Bosnia and Herzegovina" },
                new Location { City = "Mostar", Country = "Bosnia and Herzegovina" },
                new Location { City = "Banja Luka", Country = "Bosnia and Herzegovina" },
                new Location { City = "Tuzla", Country = "Bosnia and Herzegovina" },
                new Location { City = "Belgrade", Country = "Serbia" },
                new Location { City = "Zagreb", Country = "Croatia" },
                new Location { City = "New York", Country = "USA" },
                new Location { City = "San Francisco", Country = "USA" },
                new Location { City = "London", Country = "UK" },
                new Location { City = "Berlin", Country = "Germany" },
                new Location { City = "Amsterdam", Country = "Netherlands" },
                new Location { City = "Remote", Country = "Global" }
            );
            dbContext.SaveChanges();
        }

        private static void SeedUsersAndProfiles(ITapplyDbContext dbContext)
        {
            var adminRole = dbContext.Roles.Find(1)!;
            var candidateRole = dbContext.Roles.Find(2)!;
            var employerRole = dbContext.Roles.Find(3)!;
            var locations = dbContext.Locations.ToList();
            var logoBytes = Convert.FromBase64String(PngBase64);
            var cvBytes = Convert.FromBase64String(PdfBase64);

            var adminUser = CreateUser("admin@itapply.com", "test");
            dbContext.Users.Add(adminUser);
            dbContext.UserRoles.Add(new UserRole { User = adminUser, Role = adminRole });

            var candidates = new List<Candidate>
            {
                new Candidate { User = CreateUser("candidate1@itapply.com", "test"), FirstName = "Tarik", LastName = "Kukuljac", Title = ".NET Developer", PhoneNumber = "+38761111111", ExperienceLevel = ExperienceLevel.Senior, ExperienceYears = 8, Location = locations[0], Bio = "Senior .NET developer with a passion for clean architecture and microservices." },
                new Candidate { User = CreateUser("candidate2@itapply.com", "test"), FirstName = "Ben", LastName = "Carter", Title = "Frontend Engineer", PhoneNumber = "+442071234567", ExperienceLevel = ExperienceLevel.Senior, ExperienceYears = 7, Location = locations[8], Bio = "Creative frontend developer specializing in React, TypeScript, and modern UI/UX principles." },
                new Candidate { User = CreateUser("candidate3@itapply.com", "test"), FirstName = "Chloe", LastName = "Davis", Title = "DevOps Engineer", PhoneNumber = "+12125550103", ExperienceLevel = ExperienceLevel.Mid, ExperienceYears = 5, Location = locations[6], Bio = "DevOps enthusiast focused on automation, CI/CD, and cloud infrastructure on AWS and Azure." },
                new Candidate { User = CreateUser("candidate4@itapply.com", "test"), FirstName = "Arman", LastName = "Basovic", Title = "Data Scientist", PhoneNumber = "+38164111222", ExperienceLevel = ExperienceLevel.Mid, ExperienceYears = 4, Location = locations[4], Bio = "Data scientist skilled in Python, machine learning, and telling stories with data." },
                new Candidate { User = CreateUser("candidate5@itapply.com", "test"), FirstName = "Velid", LastName = "Madzak", Title = "Full-Stack Developer", PhoneNumber = "+38765222333", ExperienceLevel = ExperienceLevel.Mid, ExperienceYears = 6, Location = locations[1], Bio = "Versatile full-stack developer comfortable with both .NET backends and React frontends." },
                new Candidate { User = CreateUser("candidate6@itapply.com", "test"), FirstName = "Bakir", LastName = "Kustura", Title = "Junior Software Developer", PhoneNumber = "+38762333444", ExperienceLevel = ExperienceLevel.Junior, ExperienceYears = 1, Location = locations[2], Bio = "Eager junior developer with a solid foundation in Java and SQL, looking to grow." },
                new Candidate { User = CreateUser("candidate7@itapply.com", "test"), FirstName = "Grace", LastName = "Lee", Title = "iOS Developer", PhoneNumber = "+14155550107", ExperienceLevel = ExperienceLevel.Mid, ExperienceYears = 4, Location = locations[7], Bio = "Dedicated iOS developer with experience building high-quality mobile applications using Swift and SwiftUI." },
                new Candidate { User = CreateUser("candidate8@itapply.com", "test"), FirstName = "Hajrudin", LastName = "Imamovic", Title = "QA Engineer", PhoneNumber = "+38761444555", ExperienceLevel = ExperienceLevel.Mid, ExperienceYears = 5, Location = locations[0], Bio = "Detail-oriented QA Engineer with a strong background in both manual and automated testing." },
                new Candidate { User = CreateUser("candidate9@itapply.com", "test"), FirstName = "Benjamin", LastName = "Bazdar", Title = "Python Developer", PhoneNumber = "+38591555666", ExperienceLevel = ExperienceLevel.Mid, ExperienceYears = 3, Location = locations[5], Bio = "Python developer specializing in web applications with Django and Flask." },
                new Candidate { User = CreateUser("candidate10@itapply.com", "test"), FirstName = "Amar", LastName = "Kukuljac", Title = "Junior UI/UX Designer", PhoneNumber = "+38765555666", ExperienceLevel = ExperienceLevel.Junior, ExperienceYears = 1, Location = locations[1], Bio = "Creative junior designer with skills in Figma and a passion for user-centered design." }
            };

            dbContext.Candidates.AddRange(candidates);
            foreach (var candidate in candidates) { dbContext.UserRoles.Add(new UserRole { User = candidate.User, Role = candidateRole }); }
            dbContext.SaveChanges();

            var savedCandidates = dbContext.Candidates.ToList();
            foreach (var candidate in savedCandidates) { dbContext.CVDocuments.Add(new CVDocument { CandidateId = candidate.Id, FileName = $"{candidate.FirstName}_{candidate.LastName}_CV.pdf", FileContent = cvBytes, UploadDate = DateTime.Now, IsMain = true }); }

            var employers = new List<Employer>
            {
                new Employer { User = CreateUser("employer1@itapply.com", "test"), CompanyName = "Innovatech Solutions", Address = "123 Tech Park, Sarajevo", Benefits = "Health, Dental, Vision, 401k", ContactEmail = "hr@innovatech.com", ContactPhone = "+38733123456", Industry = "Enterprise Software", YearsInBusiness=15, Size="500-1000", Location=locations[0], Website="https://innovatech.example.com", VerificationStatus=VerificationStatus.Approved, Logo=logoBytes, Description="Leading innovator in enterprise resource planning software." },
                new Employer { User = CreateUser("employer2@itapply.com", "test"), CompanyName = "CloudNet Dynamics", Address = "456 Cloud Ave, New York", Benefits = "Remote-first, Unlimited PTO, Stock Options", ContactEmail = "jobs@cloudnet.com", ContactPhone = "+12125550102", Industry = "Cloud Computing", YearsInBusiness=8, Size="100-250", Location=locations[6], Website="https://cloudnet.example.com", VerificationStatus=VerificationStatus.Approved, Logo=logoBytes, Description="Providing scalable cloud solutions and DevOps consultancy." },
                new Employer { User = CreateUser("employer3@itapply.com", "test"), CompanyName = "PixelPerfect Inc.", Address = "789 Design Blvd, San Francisco", Benefits = "Creative stipend, Flexible hours", ContactEmail = "talent@pixelperfect.com", ContactPhone = "+14155550103", Industry = "Web & Mobile Apps", YearsInBusiness=6, Size="50-100", Location=locations[7], Website="https://pixelperfect.example.com", VerificationStatus=VerificationStatus.Approved, Logo=logoBytes, Description="Crafting beautiful and intuitive user experiences for web and mobile." },
                new Employer { User = CreateUser("employer4@itapply.com", "test"), CompanyName = "Data Insights Corp.", Address = "101 Analytics Way, London", Benefits = "Conference budget, Catered lunches", ContactEmail = "careers@datainsights.com", ContactPhone = "+442079460104", Industry = "Data Analytics", YearsInBusiness=10, Size="250-500", Location=locations[8], Website="https://datainsights.example.com", VerificationStatus=VerificationStatus.Approved, Logo=logoBytes, Description="Unlocking the power of data through machine learning and analytics." },
                new Employer { User = CreateUser("employer5@itapply.com", "test"), CompanyName = "NextGen Systems", Address = "210 Future Road, Berlin", Benefits = "Pension plan, Company car", ContactEmail = "contact@nextgen-systems.com", ContactPhone = "+493012345678", Industry = "Information Technology", YearsInBusiness=20, Size="1000+", Location=locations[9], Website="https://nextgen.example.com", VerificationStatus=VerificationStatus.Approved, Logo=logoBytes, Description="A global leader in IT services and consulting." },
                new Employer { User = CreateUser("employer6@itapply.com", "test"), CompanyName = "SoftComp", Address = "333 Ulica, Belgrade", Benefits = "Private health insurance, Gym membership", ContactEmail = "apply@softcomp.com", ContactPhone = "+381112345678", Industry = "Software Development", YearsInBusiness=12, Size="100-250", Location=locations[4], Website="https://softcomp.example.com", VerificationStatus=VerificationStatus.Approved, Logo=logoBytes, Description="Custom software development house based in Belgrade." },
                new Employer { User = CreateUser("employer7@itapply.com", "test"), CompanyName = "CodeWeavers", Address = "444 Ulica, Zagreb", Benefits = "Indie game launch bonuses", ContactEmail = "info@codeweavers.com", ContactPhone = "+38514812345", Industry = "Game Development", YearsInBusiness=5, Size="20-50", Location=locations[5], Website="https://codeweavers.example.com", VerificationStatus=VerificationStatus.Pending, Logo=logoBytes, Description="Small, passionate studio creating indie games." },
                new Employer { User = CreateUser("employer8@itapply.com", "test"), CompanyName = "OldTech Co.", Address = "555 Legacy Lane, Tuzla", Benefits = "Stable job, Standard benefits", ContactEmail = "hr@oldtech.com", ContactPhone = "+38735123456", Industry = "Legacy Systems", YearsInBusiness=30, Size="500-1000", Location=locations[3], Website="https://oldtech.example.com", VerificationStatus=VerificationStatus.Rejected, Logo=logoBytes, Description="Maintaining legacy enterprise systems." }
            };

            dbContext.Employers.AddRange(employers);
            foreach (var employer in employers) { dbContext.UserRoles.Add(new UserRole { User = employer.User, Role = employerRole }); }

            dbContext.SaveChanges();
        }

        private static void SeedJobPostings(ITapplyDbContext dbContext)
        {
            var employers = dbContext.Employers.Where(e => e.VerificationStatus == VerificationStatus.Approved).ToList();
            var locations = dbContext.Locations.ToList();
            var jobPostings = new List<JobPosting>
            {
                new JobPosting { Title = "Senior .NET Engineer", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=100000, MaxSalary=140000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-10), ApplicationDeadline = DateTime.Now.AddDays(30) },
                new JobPosting { Title = "Backend Developer (C#)", Employer = employers[4], Location = locations[9], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=80000, MaxSalary=110000, Remote=Remote.No, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-5), ApplicationDeadline = DateTime.Now.AddDays(20) },
                new JobPosting { Title = "Azure Cloud Engineer (.NET)", Employer = employers[1], Location = locations[6], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=110000, MaxSalary=150000, Remote=Remote.Yes, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-15), ApplicationDeadline = DateTime.Now.AddDays(45) },
                new JobPosting { Title = "Junior Java Developer", Employer = employers[5], Location = locations[4], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Junior, MinSalary=50000, MaxSalary=70000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-8), ApplicationDeadline = DateTime.Now.AddDays(25) },
                new JobPosting { Title = "Lead Software Engineer (.NET)", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Lead, MinSalary=130000, MaxSalary=170000, Remote=Remote.No, Status = JobPostingStatus.Closed, PostedDate = DateTime.Now.AddDays(-50), ApplicationDeadline = DateTime.Now.AddDays(-10) },
                new JobPosting { Title = "Senior React Developer", Employer = employers[2], Location = locations[7], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=100000, MaxSalary=140000, Remote=Remote.Yes, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-12), ApplicationDeadline = DateTime.Now.AddDays(30) },
                new JobPosting { Title = "UI/UX Designer", Employer = employers[2], Location = locations[7], EmploymentType = EmploymentType.Contract, ExperienceLevel = ExperienceLevel.Mid, MinSalary=70000, MaxSalary=90000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-3), ApplicationDeadline = DateTime.Now.AddDays(15) },
                new JobPosting { Title = "Frontend Developer (Vue.js)", Employer = employers[5], Location = locations[4], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=75000, MaxSalary=100000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-20), ApplicationDeadline = DateTime.Now.AddDays(50) },
                new JobPosting { Title = "Junior Frontend Intern", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.Internship, ExperienceLevel = ExperienceLevel.EntryLevel, MinSalary=20000, MaxSalary=30000, Remote=Remote.No, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-2), ApplicationDeadline = DateTime.Now.AddDays(10) },
                new JobPosting { Title = "Full-Stack Developer (.NET + React)", Employer = employers[0], Location = locations[1], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=85000, MaxSalary=115000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-18), ApplicationDeadline = DateTime.Now.AddDays(35) },
                new JobPosting { Title = "Software Engineer (Node.js + Vue)", Employer = employers[5], Location = locations[4], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=80000, MaxSalary=110000, Remote=Remote.Yes, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-9), ApplicationDeadline = DateTime.Now.AddDays(22) },
                new JobPosting { Title = "Senior DevOps Engineer (AWS)", Employer = employers[1], Location = locations[6], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=120000, MaxSalary=160000, Remote=Remote.Yes, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-25), ApplicationDeadline = DateTime.Now.AddDays(40) },
                new JobPosting { Title = "CI/CD Specialist (Jenkins/GitLab)", Employer = employers[4], Location = locations[9], EmploymentType = EmploymentType.Contract, ExperienceLevel = ExperienceLevel.Mid, MinSalary=90000, MaxSalary=120000, Remote=Remote.Yes, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-6), ApplicationDeadline = DateTime.Now.AddDays(18) },
                new JobPosting { Title = "Kubernetes Administrator", Employer = employers[1], Location = locations[8], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=95000, MaxSalary=130000, Remote=Remote.Hybrid, Status = JobPostingStatus.Closed, PostedDate = DateTime.Now.AddDays(-60), ApplicationDeadline = DateTime.Now.AddDays(-20) },
                new JobPosting { Title = "Machine Learning Engineer", Employer = employers[3], Location = locations[8], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=125000, MaxSalary=170000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-30), ApplicationDeadline = DateTime.Now.AddDays(60) },
                new JobPosting { Title = "Data Analyst (SQL & Python)", Employer = employers[3], Location = locations[8], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=80000, MaxSalary=105000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-11), ApplicationDeadline = DateTime.Now.AddDays(28) },
                new JobPosting { Title = "Big Data Engineer (Spark/Hadoop)", Employer = employers[3], Location = locations[6], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Lead, MinSalary=140000, MaxSalary=190000, Remote=Remote.Yes, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-14), ApplicationDeadline = DateTime.Now.AddDays(33) },
                new JobPosting { Title = "iOS Developer (SwiftUI)", Employer = employers[2], Location = locations[7], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=90000, MaxSalary=125000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-8), ApplicationDeadline = DateTime.Now.AddDays(26) },
                new JobPosting { Title = "Android Developer (Kotlin)", Employer = employers[2], Location = locations[7], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=90000, MaxSalary=125000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-8), ApplicationDeadline = DateTime.Now.AddDays(26) },
                new JobPosting { Title = "QA Automation Engineer", Employer = employers[4], Location = locations[9], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=70000, MaxSalary=95000, Remote=Remote.No, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-4), ApplicationDeadline = DateTime.Now.AddDays(14) },
                new JobPosting { Title = "Project Manager (Agile/Scrum)", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=90000, MaxSalary=120000, Remote=Remote.No, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-22), ApplicationDeadline = DateTime.Now.AddDays(40) },
                new JobPosting { Title = "Expired .NET Role", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=80000, MaxSalary=100000, Remote=Remote.Hybrid, Status = JobPostingStatus.Closed, PostedDate = DateTime.Now.AddDays(-40), ApplicationDeadline = DateTime.Now.AddDays(-5) },
                new JobPosting { Title = "Expired Frontend Role", Employer = employers[2], Location = locations[7], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=80000, MaxSalary=100000, Remote=Remote.Yes, Status = JobPostingStatus.Closed, PostedDate = DateTime.Now.AddDays(-50), ApplicationDeadline = DateTime.Now.AddDays(-15) },
                new JobPosting { Title = "Expired DevOps Role", Employer = employers[1], Location = locations[6], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=100000, MaxSalary=130000, Remote=Remote.Yes, Status = JobPostingStatus.Closed, PostedDate = DateTime.Now.AddDays(-45), ApplicationDeadline = DateTime.Now.AddDays(-8) },
                new JobPosting { Title = "Expired Data Role", Employer = employers[3], Location = locations[8], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=90000, MaxSalary=110000, Remote=Remote.Hybrid, Status = JobPostingStatus.Closed, PostedDate = DateTime.Now.AddDays(-35), ApplicationDeadline = DateTime.Now.AddDays(-2) },
                new JobPosting { Title = "Senior .NET Engineer", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Senior, MinSalary=100000, MaxSalary=140000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-10), ApplicationDeadline = DateTime.Now.AddDays(30) },
                new JobPosting { Title = "Medior .NET Engineer", Employer = employers[0], Location = locations[0], EmploymentType = EmploymentType.FullTime, ExperienceLevel = ExperienceLevel.Mid, MinSalary=90000, MaxSalary=120000, Remote=Remote.Hybrid, Status = JobPostingStatus.Active, PostedDate = DateTime.Now.AddDays(-10), ApplicationDeadline = DateTime.Now.AddDays(30) },
            };

            foreach (var job in jobPostings)
            {
                job.Description = $"Exciting opportunity for a {job.Title} at {job.Employer.CompanyName}. Join our dynamic team and work on cutting-edge projects in {job.Location.City}.";
                job.Requirements = $"We are looking for a {job.ExperienceLevel} professional with experience in key technologies for this role. Strong communication and teamwork skills are essential.";
                job.Benefits = $"{job.Employer.CompanyName} offers a competitive salary, {job.Employer.Benefits}, and a great work environment.";
            }

            dbContext.JobPostings.AddRange(jobPostings);
            dbContext.SaveChanges();
        }

        private static void SeedJunctionTables(ITapplyDbContext dbContext)
        {
            var skills = dbContext.Skills.ToDictionary(s => s.Name, s => s.Id);

            var jobs = dbContext.JobPostings.ToList();
            var jobSkills = new List<JobPostingSkill>();
            Action<int, string[]> linkJob = (jobId, skillNames) => {
                jobSkills.AddRange(skillNames.Where(skills.ContainsKey).Select(skillName => new JobPostingSkill { JobPostingId = jobId, SkillId = skills[skillName] }));
            };

            linkJob(jobs[0].Id, new[] { "C#", ".NET Core", "SQL", "Azure", "GraphQL" });
            linkJob(jobs[1].Id, new[] { "C#", ".NET Core", "SQL", "Git" });
            linkJob(jobs[2].Id, new[] { ".NET Core", "Azure", "Docker", "Kubernetes", "CI/CD" });
            linkJob(jobs[3].Id, new[] { "Java", "SQL" });
            linkJob(jobs[4].Id, new[] { "C#", ".NET Core", "Project Management" });
            linkJob(jobs[5].Id, new[] { "React", "TypeScript", "JavaScript", "HTML", "CSS" });
            linkJob(jobs[6].Id, new[] { "UI/UX Design", "Figma", "Sketch" });
            linkJob(jobs[7].Id, new[] { "Vue.js", "JavaScript", "HTML", "CSS" });
            linkJob(jobs[8].Id, new[] { "React", "JavaScript", "HTML" });
            linkJob(jobs[9].Id, new[] { ".NET Core", "React", "SQL", "TypeScript" });
            linkJob(jobs[10].Id, new[] { "Node.js", "Vue.js", "MongoDB", "JavaScript" });
            linkJob(jobs[11].Id, new[] { "AWS", "Docker", "Kubernetes", "Terraform", "CI/CD" });
            linkJob(jobs[12].Id, new[] { "Jenkins", "GitLab CI", "CI/CD", "Ansible" });
            linkJob(jobs[13].Id, new[] { "Kubernetes", "Docker" });
            linkJob(jobs[14].Id, new[] { "Machine Learning", "Python", "Deep Learning" });
            linkJob(jobs[15].Id, new[] { "Data Science", "Python", "SQL", "Pandas" });
            linkJob(jobs[16].Id, new[] { "Big Data", "Apache Spark", "Hadoop", "Python" });
            linkJob(jobs[17].Id, new[] { "iOS", "Swift", "Mobile Development" });
            linkJob(jobs[18].Id, new[] { "Android", "Kotlin", "Mobile Development" });
            linkJob(jobs[19].Id, new[] { "Quality Assurance", "Selenium" });
            linkJob(jobs[20].Id, new[] { "Project Management", "Agile", "Scrum" });
            linkJob(jobs[25].Id, new[] { "C#", ".NET Core", "SQL", "Azure" });
            linkJob(jobs[26].Id, new[] { "C#", ".NET Core", "SQL" });
            dbContext.JobPostingSkills.AddRange(jobSkills);

            var candidates = dbContext.Candidates.ToList();
            var candidateSkills = new List<CandidateSkill>();
            Action<int, int, string[]> linkCand = (candidateId, level, skillNames) => {
                candidateSkills.AddRange(skillNames.Where(skills.ContainsKey).Select(skillName => new CandidateSkill { CandidateId = candidateId, SkillId = skills[skillName], Level = level }));
            };

            linkCand(candidates[0].Id, 5, new[] { "C#", ".NET Core", "SQL" }); linkCand(candidates[0].Id, 4, new[] { "Azure", "Docker" });
            linkCand(candidates[1].Id, 5, new[] { "React", "TypeScript", "JavaScript" }); linkCand(candidates[1].Id, 3, new[] { "UI/UX Design", "Node.js" });
            linkCand(candidates[2].Id, 5, new[] { "AWS", "Docker", "Kubernetes" }); linkCand(candidates[2].Id, 4, new[] { "Terraform", "Python" });
            linkCand(candidates[3].Id, 5, new[] { "Python", "Data Science", "Machine Learning" }); linkCand(candidates[3].Id, 4, new[] { "SQL", "Pandas" });
            linkCand(candidates[4].Id, 4, new[] { "C#", ".NET Core", "React", "SQL" }); linkCand(candidates[4].Id, 3, new[] { "Node.js", "Azure" });
            linkCand(candidates[5].Id, 3, new[] { "Java", "SQL", "Git" });
            linkCand(candidates[6].Id, 4, new[] { "iOS", "Swift", "Mobile Development" });
            linkCand(candidates[7].Id, 4, new[] { "Quality Assurance", "Selenium", "Agile" });
            linkCand(candidates[8].Id, 4, new[] { "Python", "SQL" });
            linkCand(candidates[9].Id, 3, new[] { "UI/UX Design", "Figma" });
            dbContext.CandidateSkills.AddRange(candidateSkills);

            var employers = dbContext.Employers.ToList();
            var employerSkills = new List<EmployerSkill>();
            Action<int, string[]> linkEmp = (employerId, skillNames) => {
                employerSkills.AddRange(skillNames.Where(skills.ContainsKey).Select(skillName => new EmployerSkill { EmployerId = employerId, SkillId = skills[skillName] }));
            };

            linkEmp(employers[0].Id, new[] { "C#", ".NET Core", "SQL", "Azure", "Agile" });
            linkEmp(employers[1].Id, new[] { "AWS", "Azure", "GCP", "Docker", "Kubernetes", "DevOps" });
            linkEmp(employers[2].Id, new[] { "React", "TypeScript", "UI/UX Design", "iOS", "Android" });
            linkEmp(employers[3].Id, new[] { "Python", "Data Science", "Machine Learning", "Big Data" });
            dbContext.EmployerSkills.AddRange(employerSkills);

            dbContext.SaveChanges();
        }

        private static void SeedApplications(ITapplyDbContext dbContext)
        {
            var candidates = dbContext.Candidates.ToList();
            var jobs = dbContext.JobPostings.ToList();
            var cvs = dbContext.CVDocuments.ToList();

            Func<string, int> getJobId = (title) => jobs.First(j => j.Title == title).Id;
            var random = new Random();

            var applications = new List<Application>
            {
                new Application { CandidateId = candidates[0].Id, JobPostingId = getJobId("Senior .NET Engineer"), Status = ApplicationStatus.InterviewScheduled, CVDocumentId = cvs.First(c => c.CandidateId == candidates[0].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[0].Id, JobPostingId = getJobId("Backend Developer (C#)"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[0].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[0].Id, JobPostingId = getJobId("Azure Cloud Engineer (.NET)"), Status = ApplicationStatus.InConsideration, CVDocumentId = cvs.First(c => c.CandidateId == candidates[0].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[0].Id, JobPostingId = getJobId("Expired .NET Role"), Status = ApplicationStatus.Rejected, CVDocumentId = cvs.First(c => c.CandidateId == candidates[0].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[1].Id, JobPostingId = getJobId("Senior React Developer"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[1].Id).Id, Availability = "2 weeks notice" },
                new Application { CandidateId = candidates[1].Id, JobPostingId = getJobId("UI/UX Designer"), Status = ApplicationStatus.InConsideration, CVDocumentId = cvs.First(c => c.CandidateId == candidates[1].Id).Id, Availability = "2 weeks notice" },
                new Application { CandidateId = candidates[1].Id, JobPostingId = getJobId("Frontend Developer (Vue.js)"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[1].Id).Id, Availability = "2 weeks notice" },
                new Application { CandidateId = candidates[1].Id, JobPostingId = getJobId("Full-Stack Developer (.NET + React)"), Status = ApplicationStatus.Rejected, CVDocumentId = cvs.First(c => c.CandidateId == candidates[1].Id).Id, Availability = "2 weeks notice" },
                new Application { CandidateId = candidates[1].Id, JobPostingId = getJobId("Expired Frontend Role"), Status = ApplicationStatus.Rejected, CVDocumentId = cvs.First(c => c.CandidateId == candidates[1].Id).Id, Availability = "2 weeks notice" },
                new Application { CandidateId = candidates[2].Id, JobPostingId = getJobId("Senior DevOps Engineer (AWS)"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[2].Id).Id, Availability = "1 month notice" },
                new Application { CandidateId = candidates[2].Id, JobPostingId = getJobId("CI/CD Specialist (Jenkins/GitLab)"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[2].Id).Id, Availability = "1 month notice" },
                new Application { CandidateId = candidates[3].Id, JobPostingId = getJobId("Machine Learning Engineer"), Status = ApplicationStatus.InConsideration, CVDocumentId = cvs.First(c => c.CandidateId == candidates[3].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[3].Id, JobPostingId = getJobId("Data Analyst (SQL & Python)"), Status = ApplicationStatus.InterviewScheduled, CVDocumentId = cvs.First(c => c.CandidateId == candidates[3].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[4].Id, JobPostingId = getJobId("Full-Stack Developer (.NET + React)"), Status = ApplicationStatus.Accepted, CVDocumentId = cvs.First(c => c.CandidateId == candidates[4].Id).Id, Availability = "N/A" },
                new Application { CandidateId = candidates[4].Id, JobPostingId = getJobId("Senior .NET Engineer"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[4].Id).Id, Availability = "N/A" },
                new Application { CandidateId = candidates[5].Id, JobPostingId = getJobId("Junior Java Developer"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[5].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[6].Id, JobPostingId = getJobId("iOS Developer (SwiftUI)"), Status = ApplicationStatus.InConsideration, CVDocumentId = cvs.First(c => c.CandidateId == candidates[6].Id).Id, Availability = "3 weeks notice" },
                new Application { CandidateId = candidates[7].Id, JobPostingId = getJobId("QA Automation Engineer"), Status = ApplicationStatus.InterviewScheduled, CVDocumentId = cvs.First(c => c.CandidateId == candidates[7].Id).Id, Availability = "1 week notice" },
                new Application { CandidateId = candidates[8].Id, JobPostingId = getJobId("Backend Developer (C#)"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[8].Id).Id, Availability = "Immediately" },
                new Application { CandidateId = candidates[9].Id, JobPostingId = getJobId("UI/UX Designer"), Status = ApplicationStatus.Applied, CVDocumentId = cvs.First(c => c.CandidateId == candidates[9].Id).Id, Availability = "Immediately" }
            };

            foreach (var app in applications)
            {
                app.ApplicationDate = DateTime.Now.AddDays(-random.Next(1, 60));
                app.CoverLetter = $"I am writing to express my strong interest in the {jobs.First(j => j.Id == app.JobPostingId).Title} position. My skills and experience are an excellent match for your requirements.";
            }

            dbContext.Applications.AddRange(applications);
            dbContext.SaveChanges();
        }

        private static void SeedRemainingData(ITapplyDbContext dbContext)
        {
            var candidates = dbContext.Candidates.ToList();
            var employers = dbContext.Employers.ToList();

            dbContext.Reviews.AddRange(
                new Review { CandidateId = candidates[0].Id, EmployerId = employers[0].Id, Rating = 5, Comment = "Excellent company, great team.", Position = "Senior .NET Engineer", Relationship = ReviewRelationship.FormerEmployee, ModerationStatus = ModerationStatus.Approved, ReviewDate = DateTime.Now.AddMonths(-6) },
                new Review { CandidateId = candidates[1].Id, EmployerId = employers[2].Id, Rating = 4, Comment = "Very creative environment, but fast-paced.", Position = "Frontend Developer", Relationship = ReviewRelationship.CurrentEmployee, ModerationStatus = ModerationStatus.Approved, ReviewDate = DateTime.Now.AddMonths(-2) },
                new Review { CandidateId = candidates[2].Id, EmployerId = employers[1].Id, Rating = 5, Comment = "Top-notch tech and great learning opportunities.", Position = "DevOps Engineer", Relationship = ReviewRelationship.CurrentEmployee, ModerationStatus = ModerationStatus.Approved, ReviewDate = DateTime.Now.AddMonths(-1) },
                new Review { CandidateId = candidates[4].Id, EmployerId = employers[0].Id, Rating = 4, Comment = "The interview process was very thorough and professional.", Position = "Full-Stack Developer", Relationship = ReviewRelationship.Interviewee, ModerationStatus = ModerationStatus.Approved, ReviewDate = DateTime.Now.AddMonths(-3) },
                new Review { CandidateId = candidates[3].Id, EmployerId = employers[3].Id, Rating = 3, Comment = "Good company, but some projects are less exciting than others.", Position = "Data Scientist", Relationship = ReviewRelationship.CurrentEmployee, ModerationStatus = ModerationStatus.Pending, ReviewDate = DateTime.Now.AddDays(-5) },
                new Review { CandidateId = candidates[0].Id, EmployerId = employers[4].Id, Rating = 2, Comment = "Did not receive feedback after the final interview round.", Position = "Backend Developer", Relationship = ReviewRelationship.Interviewee, ModerationStatus = ModerationStatus.Approved, ReviewDate = DateTime.Now.AddMonths(-4) }
            );

            foreach (var candidate in candidates)
            {
                dbContext.WorkExperiences.Add(new WorkExperience
                {
                    CandidateId = candidate.Id,
                    CompanyName = "Previous Company Inc.",
                    Position = candidate.Title,
                    StartDate = DateTime.Now.AddYears(-(candidate.ExperienceYears)),
                    EndDate = DateTime.Now.AddYears(-1),
                    Description = "Worked on various projects using relevant technologies."
                });
                dbContext.Educations.Add(new Education
                {
                    CandidateId = candidate.Id,
                    Institution = "Faculty of Information Technology",
                    Degree = "Bachelor",
                    FieldOfStudy = "Computer Science",
                    StartDate = DateTime.Now.AddYears(-(candidate.ExperienceYears) - 4),
                    EndDate = DateTime.Now.AddYears(-(candidate.ExperienceYears)),
                    Description = "Graduated with honors."
                });
                dbContext.Preferences.Add(new Preferences
                {
                    CandidateId = candidate.Id,
                    LocationId = candidate.LocationId,
                    Remote = Remote.Hybrid,
                    EmploymentType = EmploymentType.FullTime
                });
            }

            dbContext.SaveChanges();
        }

        private static User CreateUser(string email, string password)
        {
            byte[] salt;
            string userHashedPassword = HashPassword(password, out salt);
            string userSalt = Convert.ToBase64String(salt);

            return new User
            {
                Email = email,
                PasswordHash = userHashedPassword,
                PasswordSalt = userSalt,
                RegistrationDate = DateTime.Now.AddDays(-new Random().Next(30, 365)),
                IsActive = true
            };
        }

        private static string HashPassword(string password, out byte[] salt)
        {
            salt = new byte[16];
            using (var rng = new RNGCryptoServiceProvider())
            {
                rng.GetBytes(salt);
            }

            using (var pbkdf2 = new Rfc2898DeriveBytes(password, salt, 10000))
            {
                return Convert.ToBase64String(pbkdf2.GetBytes(32));
            }
        }
    }
}