version: '3.8'

networks:
  itapply-network:
    driver: bridge

services:
  itapply-api:
    build:
      context: .
      dockerfile: ITapply.WebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=itapply-sql;Database=220202;User=sa;Password=Password1!;TrustServerCertificate=True
    depends_on:
      - itapply-sql
    networks:
      - itapply-network
    restart: unless-stopped

  itapply-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    expose:
      - 1433
    networks:
      - itapply-network
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password1!" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s